const formatMoney=value=>new Intl.NumberFormat('vi-VN').format(value)+' ₫';
const products=[{id:1,name:'Áo thun Cotton Premium',sku:'ATC-001',price:249000,stock:42,code:'AT'},{id:2,name:'Quần vải ống suông',sku:'QVS-021',price:299000,stock:18,code:'QV'},{id:3,name:'Sơ mi Linen dài tay',sku:'SML-014',price:314000,stock:7,code:'SM'},{id:4,name:'Chân váy chữ A',sku:'CVA-008',price:249000,stock:35,code:'CV'},{id:5,name:'Túi đeo chéo Mini',sku:'TDC-016',price:189000,stock:21,code:'TĐ'},{id:6,name:'Áo Polo Pio Basic',sku:'APB-003',price:279000,stock:56,code:'AP'}];
let cart=[];const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];const productModal=$('#productModal');const posModal=$('#posModal');
function showToast(message,title='Thành công'){const toast=$('#toast');toast.querySelector('strong').textContent=title;$('#toastMessage').textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),3200)}
function setModal(modal,open){modal.classList.toggle('open',open);modal.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':''}
$$('.nav-item[data-page]').forEach(item=>item.addEventListener('click',()=>{$$('.nav-item').forEach(nav=>nav.classList.remove('active'));item.classList.add('active');$('#pageTitle').textContent=item.dataset.page;if(window.innerWidth<=820)$('#sidebar').classList.remove('open');if(item.dataset.page==='Bán hàng')setModal(posModal,true);else if(item.dataset.page!=='Tổng quan')showToast(`${item.dataset.page} sẽ được kết nối dữ liệu ở giai đoạn tiếp theo.`,'Đã chuyển phân hệ')}));
$('#menuToggle').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#addProductBtn').addEventListener('click',()=>setModal(productModal,true));$('#openPosBtn').addEventListener('click',()=>setModal(posModal,true));$$('[data-close-modal]').forEach(button=>button.addEventListener('click',()=>setModal(productModal,false)));$$('[data-close-pos]').forEach(button=>button.addEventListener('click',()=>setModal(posModal,false)));
$('#productForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const name=data.get('name'),sku=data.get('sku'),price=Number(data.get('price')),stock=Number(data.get('stock'));const row=document.createElement('tr');row.innerHTML=`<td><div class="product"><span class="product-thumb sky">${name.slice(0,2).toUpperCase()}</span><div><strong>${name}</strong><small>${data.get('category')}</small></div></div></td><td>${sku}</td><td><strong>0</strong></td><td>${stock}</td><td><strong>${formatMoney(0)}</strong></td><td><span class="status good">Đang kinh doanh</span></td><td><button class="more-btn">•••</button></td>`;$('#productTable').prepend(row);products.unshift({id:Date.now(),name,sku,price,stock,code:name.slice(0,2).toUpperCase()});renderPosProducts(products);event.currentTarget.reset();setModal(productModal,false);showToast(`Đã thêm “${name}” vào danh mục.`)});
$('#productSearch').addEventListener('input',event=>{const query=event.target.value.trim().toLowerCase();$$('#productTable tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(query))});
const ranges={today:['18.640.000 ₫','42','6.324.000 ₫','126'],week:['124.800.000 ₫','286','41.184.000 ₫','126'],month:['486.230.000 ₫','1.148','160.456.000 ₫','126']};$('#dateRange').addEventListener('change',event=>{const values=ranges[event.target.value];['revenue','orders','profit','stock'].forEach((key,index)=>document.querySelector(`[data-metric="${key}"]`).textContent=values[index]);showToast('Đã cập nhật số liệu theo khoảng thời gian.','Dữ liệu đã lọc')});
function renderPosProducts(list){$('#posProducts').innerHTML=list.map(product=>`<button class="pos-product" data-product-id="${product.id}"><span class="product-image">${product.code}</span><strong>${product.name}</strong><small>${product.sku} · Tồn ${product.stock}</small><b>${formatMoney(product.price)}</b></button>`).join('');$$('.pos-product').forEach(button=>button.addEventListener('click',()=>addToCart(Number(button.dataset.productId))))}
function addToCart(id){const product=products.find(item=>item.id===id);const existing=cart.find(item=>item.id===id);if(existing)existing.quantity+=1;else cart.push({...product,quantity:1});renderCart()}
function renderCart(){const totalQuantity=cart.reduce((sum,item)=>sum+item.quantity,0);const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);$('#cartCount').textContent=`${totalQuantity} sản phẩm`;$('#subtotal').textContent=formatMoney(total);$('#cartTotal').textContent=formatMoney(total);$('#checkoutBtn').disabled=cart.length===0;$('#cartItems').innerHTML=cart.length?cart.map(item=>`<div class="cart-line"><div><strong>${item.name}</strong><small>${item.quantity} × ${formatMoney(item.price)}</small></div><button data-remove-id="${item.id}" aria-label="Xóa">×</button></div>`).join(''):'<div class="empty-cart"><span>▤</span><strong>Chưa có sản phẩm</strong><p>Chọn sản phẩm để thêm vào đơn</p></div>';$$('[data-remove-id]').forEach(button=>button.addEventListener('click',()=>{cart=cart.filter(item=>item.id!==Number(button.dataset.removeId));renderCart()}))}
$('#posSearch').addEventListener('input',event=>{const query=event.target.value.trim().toLowerCase();renderPosProducts(products.filter(product=>`${product.name} ${product.sku}`.toLowerCase().includes(query)))});$('#checkoutBtn').addEventListener('click',()=>{const amount=$('#cartTotal').textContent;cart=[];renderCart();setModal(posModal,false);showToast(`Đơn hàng ${amount} đã được tạo thành công.`)});$$('.category-tabs button').forEach(button=>button.addEventListener('click',()=>{$$('.category-tabs button').forEach(item=>item.classList.remove('active'));button.classList.add('active')}));document.addEventListener('keydown',event=>{if(event.key==='Escape'){setModal(productModal,false);setModal(posModal,false)}if(event.key==='F2'){event.preventDefault();setModal(posModal,true)}});renderPosProducts(products);
