"use client";

import { useMemo, useRef, useState } from "react";
import { CalendarDays, Columns3, Download, FileUp, HelpCircle, Search, Settings, SlidersHorizontal, Star, Users } from "lucide-react";
import ManagementHeader from "@/app/management-header";
import type { Profile } from "@/lib/auth";

type SourceCustomer = { id: string; name: string; phone?: string | null; email?: string | null; total_spent?: number; created_at: string; created_by?: string | null };
type SourceOrder = { customer_id?: string | null; total: number; status: string; created_at: string };
type CustomerRow = SourceCustomer & { code: string; group: string; birthday: string; facebook: string; taxCode: string; identity: string; address: string; ward: string; note: string; netSales: number; debt: number; creator: string; active: boolean; favorite: boolean; gender: string; type: string; area: string; lastTransaction: string };
const columns = [["code","Mã khách hàng"],["name","Tên khách hàng"],["phone","Điện thoại"],["birthday","Ngày sinh"],["email","Email"],["facebook","Facebook"],["taxCode","Mã số thuế"],["identity","Số CCCD/CMND"],["address","Địa chỉ"],["ward","Phường/Xã"],["note","Ghi chú"],["totalSpent","Tổng bán"],["netSales","Tổng bán trừ trả hàng"],["debt","Nợ hiện tại"],["createdAt","Ngày tạo"],["status","Trạng thái"]] as const;
const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value);
const date = (value: string) => new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value));

export default function CustomersClient({ profile, initialCustomers, orders }: { profile: Profile; initialCustomers: SourceCustomer[]; orders: SourceOrder[] }) {
  const seed = useMemo<CustomerRow[]>(() => initialCustomers.map((item, index) => { const customerOrders = orders.filter((order) => order.customer_id === item.id && order.status === "paid"); return { ...item, code: `KH${String(initialCustomers.length - index).padStart(6,"0")}`, group: "Nhóm mặc định", birthday: "---", facebook: "---", taxCode: "---", identity: "---", address: "---", ward: "---", note: "---", total_spent: Number(item.total_spent || customerOrders.reduce((sum, order) => sum + Number(order.total), 0)), netSales: customerOrders.reduce((sum, order) => sum + Number(order.total), 0), debt: 0, creator: profile.full_name, active: true, favorite: false, gender: "", type: "Cá nhân", area: "", lastTransaction: customerOrders[0]?.created_at || item.created_at }; }), [initialCustomers, orders, profile.full_name]);
  const [items, setItems] = useState(seed); const [query, setQuery] = useState(""); const [showColumns, setShowColumns] = useState(false); const [showCreate, setShowCreate] = useState(false); const [notice, setNotice] = useState(""); const [status, setStatus] = useState("all"); const [type, setType] = useState("all"); const [gender, setGender] = useState("all"); const [datePreset, setDatePreset] = useState("all"); const [page, setPage] = useState(1); const importRef = useRef<HTMLInputElement>(null);
  const [visible, setVisible] = useState<Record<string,boolean>>(() => Object.fromEntries(columns.map(([key]) => [key, ["code","name","phone","email","totalSpent","netSales","debt","createdAt","status"].includes(key)])));
  const [form, setForm] = useState({ name:"", phone:"", email:"", birthday:"", gender:"", type:"Cá nhân", address:"", note:"" });
  const filtered = useMemo(() => items.filter((item) => `${item.code} ${item.name} ${item.phone || ""}`.toLowerCase().includes(query.toLowerCase()) && (status === "all" || (status === "active") === item.active) && (type === "all" || item.type === type) && (gender === "all" || item.gender === gender) && (datePreset === "all" || new Date(item.created_at).getMonth() === new Date().getMonth())), [items, query, status, type, gender, datePreset]);
  const pageSize=15, pages=Math.max(1,Math.ceil(filtered.length/pageSize)), safePage=Math.min(page,pages), rows=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
  async function createCustomer() { const response=await fetch("/api/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const result=await response.json(); if(!response.ok){setNotice(result.error);return;} const now=result.customer.created_at; setItems((current)=>[{...result.customer,code:`KH${String(current.length+1).padStart(6,"0")}`,group:"Nhóm mặc định",birthday:form.birthday||"---",facebook:"---",taxCode:"---",identity:"---",address:form.address||"---",ward:"---",note:form.note||"---",netSales:0,debt:0,creator:profile.full_name,active:true,favorite:false,gender:form.gender,type:form.type,area:"",lastTransaction:now},...current]); setShowCreate(false); setForm({name:"",phone:"",email:"",birthday:"",gender:"",type:"Cá nhân",address:"",note:""}); setNotice("Đã lưu khách hàng vào cơ sở dữ liệu."); }
  function exportCsv(){const lines=[columns.map(([,label])=>label),...filtered.map((item)=>columns.map(([key])=>key==="createdAt"?date(item.created_at):key==="status"?(item.active?"Đang hoạt động":"Ngừng hoạt động"):(item as unknown as Record<string,unknown>)[key]??"---"))];const csv=lines.map(line=>line.map(cell=>`"${String(cell).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([`\ufeff${csv}`],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="khach-hang.csv";a.click();URL.revokeObjectURL(url);}
  async function importCsv(){const file=importRef.current?.files?.[0];if(!file)return;const lines=(await file.text()).replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean).slice(1);const now=new Date().toISOString();const added=lines.map((line,index)=>{const cells=line.split(",").map(cell=>cell.replace(/^"|"$/g,"").replaceAll('""','"'));return {id:crypto.randomUUID(),code:cells[0]||`KH${Date.now()}${index}`,name:cells[1]||"Khách hàng mới",phone:cells[2]||"",email:cells[4]||"",total_spent:0,created_at:now,group:"Nhóm mặc định",birthday:cells[3]||"---",facebook:"---",taxCode:"---",identity:"---",address:"---",ward:"---",note:"---",netSales:0,debt:0,creator:profile.full_name,active:true,favorite:false,gender:"",type:"Cá nhân",area:"",lastTransaction:now};});setItems(current=>[...added,...current]);setNotice(`Đã nhập ${added.length} khách hàng trong phiên; hãy tạo migration nếu cần lưu toàn bộ trường mở rộng.`);}
  const cell=(item:CustomerRow,key:string)=>{if(key==="code"||key==="name")return <b className="purchase-link">{String((item as unknown as Record<string,unknown>)[key])}</b>;if(key==="createdAt")return date(item.created_at);if(["totalSpent","netSales","debt"].includes(key))return money(Number(key==="totalSpent"?item.total_spent:(item as unknown as Record<string,unknown>)[key]));if(key==="status")return <span className={`supplier-status ${item.active?"active":"inactive"}`}>{item.active?"Đang hoạt động":"Ngừng hoạt động"}</span>;return String((item as unknown as Record<string,unknown>)[key]||"---");};
  return <div className="kv-shell product-page business-page customers-page"><ManagementHeader profile={profile} active="customers"/><div className="product-actions business-actions"><h1>Khách hàng</h1><div className="product-toolbar"><label className="product-query"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Theo mã, tên, số điện thoại"/><SlidersHorizontal size={17}/></label><button onClick={()=>importRef.current?.click()}><FileUp size={18}/>Import file</button><input hidden type="file" accept=".csv" ref={importRef} onChange={importCsv}/><button onClick={()=>setNotice("Chức năng nhóm khách hàng đã sẵn sàng; cần bảng nhóm trong Supabase để lưu lâu dài.")}><Users size={18}/>Nhóm khách hàng</button><button className="primary" onClick={()=>setShowCreate(true)}>＋ Tạo mới</button><button onClick={exportCsv}><Download size={18}/>Xuất file</button><div className="column-control"><button aria-label="Chọn cột" onClick={()=>setShowColumns(v=>!v)}><Columns3 size={19}/></button>{showColumns&&<div className="columns-popover business-columns">{columns.map(([key,label])=><label key={key}><input type="checkbox" checked={visible[key]} onChange={()=>setVisible(current=>({...current,[key]:!current[key]}))}/>{label}</label>)}</div>}</div><button aria-label="Thiết lập"><Settings size={19}/></button><button aria-label="Hướng dẫn"><HelpCircle size={19}/></button></div></div>
    <main className="product-workspace"><aside className="product-filter-sidebar business-sidebar"><section><h2>Nhóm khách hàng <button>Tạo mới</button></h2><select><option>Tất cả các nhóm</option></select></section><section><h2>Ngày tạo</h2>{[["all","Toàn thời gian"],["month","Tháng này"],["custom","Tùy chỉnh"]].map(([value,label])=><label className="stock-radio" key={value}><input type="radio" name="customer-date" checked={datePreset===value} onChange={()=>setDatePreset(value)}/><span>{label}</span>{value==="custom"&&<CalendarDays size={17}/>}</label>)}</section><section><h2>Người tạo</h2><select><option>Chọn người tạo</option></select></section><section><h2>Loại khách hàng</h2>{[["all","Tất cả"],["Cá nhân","Cá nhân"],["Công ty","Công ty"]].map(([value,label])=><label className="stock-radio" key={value}><input type="radio" name="customer-type" checked={type===value} onChange={()=>setType(value)}/><span>{label}</span></label>)}</section><section><h2>Giới tính</h2>{[["all","Tất cả"],["Nam","Nam"],["Nữ","Nữ"]].map(([value,label])=><label className="stock-radio" key={value}><input type="radio" name="customer-gender" checked={gender===value} onChange={()=>setGender(value)}/><span>{label}</span></label>)}</section>{["Sinh nhật","Ngày giao dịch cuối","Tổng bán","Nợ hiện tại","Khu vực giao hàng"].map(label=><section key={label}><h2>{label}</h2>{label.includes("Tổng")||label.includes("Nợ")?<div className="debt-range"><input placeholder="Từ"/><input placeholder="Tới"/></div>:<select><option>{label.includes("Khu vực")?"Chọn Tỉnh/TP - Quận/Huyện":"Toàn thời gian"}</option></select>}</section>)}<section><h2>Trạng thái</h2>{[["all","Tất cả"],["active","Đang hoạt động"],["inactive","Ngừng hoạt động"]].map(([value,label])=><label className="stock-radio" key={value}><input type="radio" name="customer-status" checked={status===value} onChange={()=>setStatus(value)}/><span>{label}</span></label>)}</section></aside>
      <section className="product-content business-content">{notice&&<div className="product-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}<div className="product-table business-table"><table><thead><tr><th className="row-select"><input type="checkbox" aria-label="Chọn tất cả"/></th><th className="row-star"><Star size={16}/></th>{columns.filter(([key])=>visible[key]).map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.map(item=><tr key={item.id}><td className="row-select"><input type="checkbox" aria-label={`Chọn ${item.name}`}/></td><td className="row-star"><button aria-label="Đánh dấu" onClick={()=>setItems(current=>current.map(row=>row.id===item.id?{...row,favorite:!row.favorite}:row))}><Star size={17} fill={item.favorite?"#f5a623":"none"}/></button></td>{columns.filter(([key])=>visible[key]).map(([key])=><td className={["totalSpent","netSales","debt"].includes(key)?"number-cell":""} key={key}>{cell(item,key)}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.filter(([key])=>visible[key]).length+2}><div className="product-empty"><Users size={46}/><strong>Không tìm thấy kết quả</strong><p>Không có khách hàng phù hợp với bộ lọc hiện tại.</p></div></td></tr>}</tbody></table></div><footer className="product-pager"><span>Hiển thị {filtered.length?(safePage-1)*pageSize+1:0}–{Math.min(safePage*pageSize,filtered.length)} / {filtered.length}</span><div><button disabled={safePage===1} onClick={()=>setPage(safePage-1)}>‹</button><button className="current">{safePage}</button><button disabled={safePage===pages} onClick={()=>setPage(safePage+1)}>›</button></div></footer></section></main><a className="kv-help" href="tel:0704040044">💬 <span>0704 04 0044</span></a>
    {showCreate&&<div className="modal-backdrop"><section className="product-modal customer-modal"><header><div><h2>Thêm khách hàng</h2><p>Thông tin khách hàng và liên hệ</p></div><button onClick={()=>setShowCreate(false)}>×</button></header><div className="customer-form">{([['name','Tên khách hàng *'],['phone','Điện thoại'],['email','Email'],['birthday','Ngày sinh'],['gender','Giới tính'],['type','Loại khách hàng'],['address','Địa chỉ'],['note','Ghi chú']] as Array<[keyof typeof form,string]>).map(([key,label])=><label className={key==="address"||key==="note"?"wide":""} key={key}>{label}{key==="gender"||key==="type"?<select value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Chọn</option>{key==="gender"?<><option>Nam</option><option>Nữ</option></>:<><option>Cá nhân</option><option>Công ty</option></>}</select>:<input type={key==="birthday"?"date":"text"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}</div><footer><button onClick={()=>setShowCreate(false)}>Hủy</button><button className="primary" disabled={!form.name.trim()} onClick={createCustomer}>Lưu</button></footer></section></div>}
  </div>;
}
