import Link from "next/link";
import { Bell, Settings, ShoppingCart } from "lucide-react";
import type { Profile } from "@/lib/auth";

const ITEMS = ["Đơn hàng", "Khách hàng", "Nhân viên", "Sổ quỹ", "Báo cáo", "Bán online", "Thuế & Kế toán"];

export default function ManagementHeader({ profile, active }: { profile: Profile; active: "dashboard" | "products" | "pricebook" | "stocktakes" | "internal-use" | "damage-items" | "suppliers" | "purchase-orders" | "purchase-returns" }) {
  const initials = profile.full_name.split(" ").map((item) => item[0]).slice(-2).join("");
  return <>
    <header className="kv-header"><Link className="kv-brand" href="/dashboard"><span className="kv-brand-symbol"><i /><i /></span><strong>PioPio</strong></Link><div className="kv-header-actions"><button className="kv-round" aria-label="Thông báo"><Bell size={20} /></button><button className="kv-round" aria-label="Cài đặt"><Settings size={20} /></button><button className="kv-avatar">{initials}</button></div></header>
    <nav className="kv-horizontal-nav" aria-label="Menu quản lý"><div className="kv-horizontal-items"><Link className={`kv-top-item ${active === "dashboard" ? "active" : ""}`} href="/dashboard">Tổng quan</Link><div className="kv-nav-dropdown"><button className={`kv-top-item ${active === "products" || active === "pricebook" || active === "stocktakes" || active === "internal-use" || active === "damage-items" ? "active" : ""}`} aria-haspopup="true">Hàng hóa</button><div className="kv-submenu"><section><h3>Hàng hóa</h3><Link className={active === "products" ? "active" : ""} href="/products">Danh sách hàng hóa</Link><Link className={active === "pricebook" ? "active" : ""} href="/pricebook">Thiết lập giá</Link></section><section><h3>Kho hàng</h3><Link className={active === "stocktakes" ? "active" : ""} href="/stocktakes">Kiểm kho</Link><Link className={active === "internal-use" ? "active" : ""} href="/internal-use">Xuất dùng nội bộ</Link><Link className={active === "damage-items" ? "active" : ""} href="/damage-items">Xuất hủy</Link></section></div></div><div className="kv-nav-dropdown"><button className={`kv-top-item ${active === "suppliers" || active === "purchase-orders" || active === "purchase-returns" ? "active" : ""}`} aria-haspopup="true">Mua hàng</button><div className="kv-submenu"><section><h3>Nhà cung cấp</h3><Link className={active === "suppliers" ? "active" : ""} href="/suppliers">Nhà cung cấp</Link><span>Hóa đơn đầu vào <em>Mới</em></span></section><section><h3>Mua hàng</h3><Link className={active === "purchase-orders" ? "active" : ""} href="/purchase-orders">Nhập hàng</Link><Link className={active === "purchase-returns" ? "active" : ""} href="/purchase-returns">Trả hàng nhập</Link></section></div></div>{ITEMS.map((item) => <span className="kv-top-item" key={item}>{item}</span>)}</div><Link className="kv-sale-link" href="/sales"><ShoppingCart size={20} />Bán hàng</Link></nav>
  </>;
}
