"use client";

import { useMemo, useState } from "react";
import { CalendarDays, Check, Columns3, Download, HelpCircle, Search, Settings, SlidersHorizontal, Star } from "lucide-react";
import ManagementHeader from "@/app/management-header";
import type { Profile } from "@/lib/auth";

type Product = { id: string; name: string; sku: string; price: number; cost?: number; stock_quantity: number };
type Supplier = { id: string; name: string };
type Status = "draft" | "completed" | "cancelled";
type DocumentRow = { id: string; values: Record<string, string | number>; status: Status; favorite: boolean };
type Config = { title: string; active: "purchase-orders" | "purchase-returns"; placeholder: string; codePrefix: string; statuses: Record<Status, string>; columns: Array<{ key: string; label: string }>; visible: string[]; filters: string[] };

const CONFIGS: Record<"purchase" | "return", Config> = {
  purchase: { title: "Nhập hàng", active: "purchase-orders", placeholder: "Theo mã phiếu nhập", codePrefix: "PN", statuses: { draft: "Phiếu tạm", completed: "Đã nhập hàng", cancelled: "Đã hủy" }, columns: [{ key: "code", label: "Mã nhập hàng" }, { key: "returnCode", label: "Mã trả hàng nhập" }, { key: "time", label: "Thời gian" }, { key: "createdAt", label: "Thời gian tạo" }, { key: "updatedAt", label: "Ngày cập nhật" }, { key: "supplierCode", label: "Mã NCC" }, { key: "supplier", label: "Nhà cung cấp" }, { key: "branch", label: "Chi nhánh" }, { key: "handler", label: "Người nhập" }, { key: "creator", label: "Người tạo" }, { key: "totalQty", label: "Tổng số lượng" }, { key: "itemCount", label: "Số lượng mặt hàng" }, { key: "subtotal", label: "Tổng tiền hàng" }, { key: "discount", label: "Giảm giá" }, { key: "payable", label: "Cần trả NCC" }, { key: "paymentDiscount", label: "Chiết khấu thanh toán" }, { key: "paid", label: "Tiền đã trả NCC" }, { key: "note", label: "Ghi chú" }, { key: "status", label: "Trạng thái" }, { key: "invoice", label: "Số hóa đơn đầu vào" }], visible: ["code", "time", "supplier", "branch", "handler", "totalQty", "itemCount", "subtotal", "payable", "paid", "note", "status"], filters: ["Trạng thái", "Thời gian", "Người tạo", "Số hóa đơn đầu vào", "Người nhập"] },
  return: { title: "Trả hàng nhập", active: "purchase-returns", placeholder: "Theo mã trả hàng nhập", codePrefix: "THN", statuses: { draft: "Phiếu tạm", completed: "Đã trả hàng", cancelled: "Đã hủy" }, columns: [{ key: "code", label: "Mã trả hàng nhập" }, { key: "purchaseCode", label: "Mã nhập hàng" }, { key: "time", label: "Thời gian" }, { key: "createdAt", label: "Thời gian tạo" }, { key: "supplier", label: "Nhà cung cấp" }, { key: "branch", label: "Chi nhánh" }, { key: "handler", label: "Người trả" }, { key: "creator", label: "Người tạo" }, { key: "note", label: "Ghi chú" }, { key: "totalQty", label: "Tổng số lượng" }, { key: "itemCount", label: "Số lượng mặt hàng" }, { key: "subtotal", label: "Tổng tiền hàng" }, { key: "discount", label: "Giảm giá" }, { key: "payable", label: "NCC cần trả" }, { key: "paid", label: "NCC đã trả" }, { key: "status", label: "Trạng thái" }], visible: ["code", "purchaseCode", "time", "supplier", "branch", "handler", "totalQty", "itemCount", "subtotal", "payable", "paid", "note", "status"], filters: ["Trạng thái", "Thời gian", "Người tạo", "Người trả"] },
};
const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value); const dateTime = (value: string) => new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

export default function PurchaseDocumentClient({ mode, profile, products, suppliers }: { mode: "purchase" | "return"; profile: Profile; products: Product[]; suppliers: Supplier[] }) {
  const config = CONFIGS[mode]; const [rows, setRows] = useState<DocumentRow[]>([]); const [query, setQuery] = useState(""); const [invoiceQuery, setInvoiceQuery] = useState(""); const [statuses, setStatuses] = useState<Status[]>(["draft", "completed", "cancelled"]); const [datePreset, setDatePreset] = useState("month"); const [creatorFilter, setCreatorFilter] = useState("all"); const [handlerFilter, setHandlerFilter] = useState("all"); const [showCreate, setShowCreate] = useState(false); const [showColumns, setShowColumns] = useState(false); const [notice, setNotice] = useState(""); const [page, setPage] = useState(1);
  const [supplierId, setSupplierId] = useState(suppliers[0]?.id || ""); const [note, setNote] = useState(""); const [invoice, setInvoice] = useState(""); const [sourceCode, setSourceCode] = useState(""); const [productQuery, setProductQuery] = useState(""); const [quantities, setQuantities] = useState<Record<string, number>>({}); const [prices, setPrices] = useState<Record<string, number>>(() => Object.fromEntries(products.map((product) => [product.id, Number(product.cost || product.price || 0)]))); const [visible, setVisible] = useState<Record<string, boolean>>(() => Object.fromEntries(config.columns.map((column) => [column.key, config.visible.includes(column.key)])));
  const filtered = useMemo(() => rows.filter((row) => { const text = `${row.values.code || ""} ${row.values.note || ""}`.toLowerCase().includes(query.toLowerCase()); const invoiceMatch = mode === "return" || String(row.values.invoice || "").toLowerCase().includes(invoiceQuery.toLowerCase()); const created = new Date(String(row.values.createdAt)); const now = new Date(); const date = datePreset === "all" || (datePreset === "today" ? created.toDateString() === now.toDateString() : created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear()); return text && invoiceMatch && statuses.includes(row.status) && (creatorFilter === "all" || row.values.creator === creatorFilter) && (handlerFilter === "all" || row.values.handler === handlerFilter) && date; }), [rows, query, invoiceQuery, mode, statuses, datePreset, creatorFilter, handlerFilter]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / 15)); const safePage = Math.min(page, totalPages); const pageRows = filtered.slice((safePage - 1) * 15, safePage * 15); const modalProducts = products.filter((product) => `${product.sku} ${product.name}`.toLowerCase().includes(productQuery.toLowerCase())).slice(0, 40); const selectedCount = Object.values(quantities).filter((value) => value > 0).length;
  function toggleStatus(status: Status) { setStatuses((current) => current.includes(status) ? current.filter((value) => value !== status) : [...current, status]); }
  function saveDocument(status: Exclude<Status, "cancelled">) { const selected = products.filter((product) => Number(quantities[product.id] || 0) > 0); if (!selected.length) return; const now = new Date(); const totalQty = selected.reduce((sum, product) => sum + Number(quantities[product.id]), 0); const subtotal = selected.reduce((sum, product) => sum + Number(quantities[product.id]) * Number(prices[product.id] || 0), 0); const supplier = suppliers.find((item) => item.id === supplierId); const code = `${config.codePrefix}${String(Date.now()).slice(-8)}`; const values: Record<string, string | number> = { code, returnCode: "---", purchaseCode: sourceCode || "---", time: now.toISOString(), createdAt: now.toISOString(), updatedAt: now.toISOString(), supplierCode: supplier ? `NCC${supplier.id.slice(0, 6).toUpperCase()}` : "---", supplier: supplier?.name || "Chưa chọn", branch: "Chi nhánh trung tâm", handler: profile.full_name, creator: profile.full_name, totalQty, itemCount: selected.length, subtotal, discount: 0, payable: subtotal, paymentDiscount: 0, paid: status === "completed" ? subtotal : 0, note: note.trim() || "---", invoice: invoice.trim() || "---" }; setRows((current) => [{ id: crypto.randomUUID(), values, status, favorite: false }, ...current]); setShowCreate(false); setQuantities({}); setNote(""); setInvoice(""); setSourceCode(""); setNotice(`Đã ${status === "draft" ? "lưu tạm" : "hoàn thành"} phiếu trong phiên làm việc; tồn kho và công nợ chưa được cập nhật vào Supabase.`); }
  function exportCsv() { const lines = [config.columns.map((column) => column.label), ...filtered.map((row) => config.columns.map((column) => column.key === "status" ? config.statuses[row.status] : row.values[column.key] ?? "---"))]; const csv = lines.map((line) => line.map((cell) => `"${String(cell).replaceAll("\"", "\"\"")}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `${config.active}.csv`; a.click(); URL.revokeObjectURL(url); }
  function renderCell(row: DocumentRow, key: string) { if (key === "code" || key === "purchaseCode") return <b className="purchase-link">{row.values[key]}</b>; if (["time", "createdAt", "updatedAt"].includes(key)) return dateTime(String(row.values[key])); if (["subtotal", "discount", "payable", "paymentDiscount", "paid"].includes(key)) return money(Number(row.values[key] || 0)); if (key === "status") return <span className={`stock-status ${row.status === "completed" ? "balanced" : row.status}`}>{config.statuses[row.status]}</span>; return String(row.values[key] ?? "---"); }
  return <div className="kv-shell product-page purchasing-page purchase-document-page"><ManagementHeader profile={profile} active={config.active} /><div className="product-actions purchase-actions"><h1>{config.title}</h1><div className="product-toolbar"><label className="product-query"><Search size={20} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={config.placeholder} /><SlidersHorizontal size={17} /></label><button className="primary" onClick={() => setShowCreate(true)}>＋ {config.title}</button><button onClick={exportCsv}><Download size={18} />Xuất file</button><div className="column-control"><button aria-label="Chọn cột" onClick={() => setShowColumns((value) => !value)}><Columns3 size={19} /></button>{showColumns && <div className="columns-popover purchase-columns">{config.columns.map((column) => <label key={column.key}><input type="checkbox" checked={visible[column.key]} onChange={() => setVisible((current) => ({ ...current, [column.key]: !current[column.key] }))} />{column.label}</label>)}</div>}</div><button aria-label="Thiết lập"><Settings size={19} /></button><button aria-label="Hướng dẫn"><HelpCircle size={19} /></button></div></div>
    <main className="product-workspace"><aside className="product-filter-sidebar purchase-sidebar"><section><h2>Trạng thái</h2>{(["draft", "completed", "cancelled"] as Status[]).map((value) => <label className="stock-check" key={value}><input type="checkbox" checked={statuses.includes(value)} onChange={() => toggleStatus(value)} />{config.statuses[value]}</label>)}</section><section><h2>Thời gian</h2><label className="stock-radio"><input type="radio" name={`${mode}-date`} checked={datePreset === "month"} onChange={() => setDatePreset("month")} /><span>Tháng này</span></label><label className="stock-radio"><input type="radio" name={`${mode}-date`} checked={datePreset === "today"} onChange={() => setDatePreset("today")} /><span>Tùy chỉnh</span><CalendarDays size={17} /></label><label className="stock-radio"><input type="radio" name={`${mode}-date`} checked={datePreset === "all"} onChange={() => setDatePreset("all")} /><span>Toàn thời gian</span></label></section><section><h2>Người tạo</h2><select value={creatorFilter} onChange={(event) => setCreatorFilter(event.target.value)}><option value="all">Chọn người tạo</option><option value={profile.full_name}>{profile.full_name}</option></select></section>{mode === "purchase" && <section><h2>Số hóa đơn đầu vào</h2><input value={invoiceQuery} onChange={(event) => setInvoiceQuery(event.target.value)} placeholder="Theo số hóa đơn đầu vào" /></section>}<section><h2>{mode === "purchase" ? "Người nhập" : "Người trả"}</h2><select value={handlerFilter} onChange={(event) => setHandlerFilter(event.target.value)}><option value="all">Chọn người {mode === "purchase" ? "nhập" : "trả"}</option><option value={profile.full_name}>{profile.full_name}</option></select></section></aside>
      <section className="product-content purchase-content">{notice && <div className="product-notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}<div className="product-table purchase-table"><table><thead><tr><th className="row-select"><input type="checkbox" aria-label="Chọn tất cả" /></th><th className="row-star"><Star size={16} /></th>{config.columns.filter((column) => visible[column.key]).map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{pageRows.map((row) => <tr key={row.id}><td className="row-select"><input type="checkbox" aria-label={`Chọn ${row.values.code}`} /></td><td className="row-star"><Star size={17} fill={row.favorite ? "#f5a623" : "none"} /></td>{config.columns.filter((column) => visible[column.key]).map((column) => <td className={["subtotal", "discount", "payable", "paid", "totalQty", "itemCount"].includes(column.key) ? "number-cell" : ""} key={column.key}>{renderCell(row, column.key)}</td>)}</tr>)}{!pageRows.length && <tr><td colSpan={config.columns.filter((column) => visible[column.key]).length + 2}><div className="product-empty"><Columns3 size={46} /><strong>Không tìm thấy kết quả</strong><p>Không có phiếu {config.title.toLowerCase()} phù hợp với bộ lọc hiện tại.</p></div></td></tr>}</tbody></table></div><footer className="product-pager"><span>Hiển thị {filtered.length ? (safePage - 1) * 15 + 1 : 0}–{Math.min(safePage * 15, filtered.length)} / {filtered.length} phiếu</span><div><button disabled={safePage === 1} onClick={() => setPage(safePage - 1)}>‹</button><button className="current">{safePage}</button><button disabled={safePage === totalPages} onClick={() => setPage(safePage + 1)}>›</button></div></footer></section></main><a className="kv-help" href="tel:0704040044">💬 <span>0704 04 0044</span></a>
    {showCreate && <div className="modal-backdrop"><section className="product-modal purchase-modal"><header><div><h2>{config.title}</h2><p>{mode === "purchase" ? "Lập phiếu nhập hàng từ nhà cung cấp" : "Lập phiếu trả hàng cho nhà cung cấp"}</p></div><button onClick={() => setShowCreate(false)}>×</button></header><div className="purchase-form-head"><label>Nhà cung cấp<select value={supplierId} onChange={(event) => setSupplierId(event.target.value)}><option value="">Chọn nhà cung cấp</option>{suppliers.map((supplier) => <option value={supplier.id} key={supplier.id}>{supplier.name}</option>)}</select></label>{mode === "purchase" ? <label>Số hóa đơn đầu vào<input value={invoice} onChange={(event) => setInvoice(event.target.value)} /></label> : <label>Mã nhập hàng<input value={sourceCode} onChange={(event) => setSourceCode(event.target.value)} /></label>}<label>Ghi chú<input value={note} onChange={(event) => setNote(event.target.value)} /></label></div><label className="product-query purchase-product-search"><Search size={18} /><input value={productQuery} onChange={(event) => setProductQuery(event.target.value)} placeholder="Theo mã, tên hàng" /></label><div className="purchase-lines"><table><thead><tr><th>Mã hàng</th><th>Tên hàng</th><th>Tồn kho</th><th>Số lượng</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>{modalProducts.map((product) => { const quantity = Number(quantities[product.id] || 0); const price = Number(prices[product.id] || 0); return <tr key={product.id}><td>{product.sku}</td><td>{product.name}</td><td>{product.stock_quantity}</td><td><input aria-label={`Số lượng ${product.name}`} type="number" min="0" value={quantity} onChange={(event) => setQuantities((current) => ({ ...current, [product.id]: Math.max(0, Number(event.target.value)) }))} /></td><td><input aria-label={`Đơn giá ${product.name}`} type="number" min="0" value={price} onChange={(event) => setPrices((current) => ({ ...current, [product.id]: Math.max(0, Number(event.target.value)) }))} /></td><td>{money(quantity * price)}</td></tr>})}{!modalProducts.length && <tr><td colSpan={6}>Không có hàng hóa</td></tr>}</tbody></table></div>{selectedCount === 0 && <p className="purchase-warning">Nhập số lượng cho ít nhất một hàng hóa để lưu phiếu.</p>}<footer><span>{selectedCount} hàng hóa được chọn</span><button onClick={() => setShowCreate(false)}>Hủy</button><button disabled={selectedCount === 0} onClick={() => saveDocument("draft")}>Lưu tạm</button><button disabled={selectedCount === 0} className="primary" onClick={() => saveDocument("completed")}><Check size={17} />Hoàn thành</button></footer></section></div>}
  </div>;
}
