"use client";

import { useMemo, useRef, useState } from "react";
import { CalendarDays, Check, Columns3, Download, FileUp, HelpCircle, Search, Settings, SlidersHorizontal, Star } from "lucide-react";
import ManagementHeader from "@/app/management-header";
import type { Profile } from "@/lib/auth";

type Mode = "orders" | "invoices" | "returns" | "delivery-partners" | "waybills";
type Status = "draft" | "completed" | "cancelled";
type Product = { id: string; sku: string; name: string; price: number; stock_quantity: number };
type Customer = { id: string; name: string; phone?: string | null };
type SourceOrder = { id: string; order_number: number; status: string; subtotal: number; discount: number; total: number; created_at: string; updated_at?: string; customers?: { name?: string; phone?: string } | null };
type GridRow = { id: string; values: Record<string, string | number>; status: Status; favorite: boolean };
type Config = { title: string; active: Mode; placeholder: string; prefix: string; primary?: string; secondary?: string; import?: boolean; columns: Array<{ key: string; label: string }>; visible: string[]; filters: string[]; statuses: Record<Status, string> };

const C = (pairs: Array<[string, string]>) => pairs.map(([key, label]) => ({ key, label }));
const configs: Record<Mode, Config> = {
  orders: { title: "Đặt hàng", active: "orders", placeholder: "Theo mã phiếu đặt", prefix: "DH", primary: "Đặt hàng", secondary: "Gộp đơn", statuses: { draft: "Phiếu tạm", completed: "Hoàn thành", cancelled: "Đã hủy" }, columns: C([["waybill","Mã vận đơn"],["code","Mã đặt hàng"],["invoice","Mã hóa đơn"],["time","Thời gian"],["createdAt","Thời gian tạo"],["updatedAt","Ngày cập nhật"],["deliveryAt","Thời gian giao hàng"],["waitingDays","Số ngày chờ"],["customerCode","Mã KH"],["customer","Khách hàng"],["phone","Điện thoại"],["address","Địa chỉ"],["area","Khu vực"],["birthday","Ngày sinh"],["partner","Đối tác giao hàng"],["handler","Người nhận đặt"],["creator","Người tạo"],["channel","Kênh bán"],["note","Ghi chú"],["subtotal","Tổng tiền hàng"],["discount","Giảm giá"],["payable","Khách cần trả"],["paid","Khách đã trả"],["status","Trạng thái"]]), visible: ["code","time","customer","phone","handler","subtotal","discount","payable","paid","status"], filters: ["Thời gian","Trạng thái","Đối tác giao hàng","Thời gian giao hàng","Khu vực giao hàng","Phương thức thanh toán","Người tạo","Người nhận đặt","Kênh bán"] },
  invoices: { title: "Hóa đơn", active: "invoices", placeholder: "Theo mã hóa đơn", prefix: "HD", primary: "Tạo mới", import: true, statuses: { draft: "Đang xử lý", completed: "Hoàn thành", cancelled: "Đã hủy" }, columns: C([["code","Mã hóa đơn"],["waybill","Mã vận đơn"],["deliveryStatus","Trạng thái giao hàng"],["reconciliation","Mã đối soát"],["time","Thời gian"],["createdAt","Thời gian tạo"],["updatedAt","Ngày cập nhật"],["orderCode","Mã đặt hàng"],["returnCode","Mã trả hàng"],["customerCode","Mã KH"],["customer","Khách hàng"],["phone","Điện thoại"],["address","Địa chỉ"],["area","Khu vực"],["birthday","Ngày sinh"],["branch","Chi nhánh"],["handler","Người bán"],["creator","Người tạo"],["channel","Kênh bán"],["partner","Đối tác giao hàng"],["note","Ghi chú"],["subtotal","Tổng tiền hàng"],["discount","Giảm giá"],["taxDiscount","Giảm thuế"],["payable","Khách cần trả"],["paid","Khách đã trả"],["paymentDiscount","Chiết khấu thanh toán"],["cod","Còn cần thu (COD)"],["shippingFee","Phí trả ĐTGH"],["deliveryNote","Ghi chú trạng thái giao hàng"],["deliveryAt","Thời gian giao hàng"],["status","Trạng thái"]]), visible: ["code","time","customer","branch","handler","subtotal","discount","payable","paid","status"], filters: ["Thời gian","Giao hàng","Trạng thái giao hàng","Đối tác giao hàng","Thời gian giao hàng","Khu vực giao hàng","Phương thức thanh toán","Người tạo","Người bán","Bảng giá","Kênh bán"] },
  returns: { title: "Trả hàng", active: "returns", placeholder: "Theo mã phiếu trả", prefix: "TH", primary: "Trả hàng", statuses: { draft: "Phiếu tạm", completed: "Đã trả", cancelled: "Đã hủy" }, columns: C([["code","Mã trả hàng"],["invoice","Mã hóa đơn"],["waybill","Mã vận đơn bán"],["seller","Người bán"],["time","Thời gian"],["createdAt","Thời gian tạo"],["customerCode","Mã KH"],["customer","Khách hàng"],["branch","Chi nhánh"],["handler","Người nhận trả"],["creator","Người tạo"],["channel","Kênh bán"],["note","Ghi chú"],["subtotal","Tổng tiền hàng"],["discount","Giảm giá"],["afterDiscount","Tổng sau giảm giá"],["taxRefund","Giảm thuế hoàn lại"],["returnFee","Phí trả hàng"],["otherRefund","Thu khác hoàn lại"],["payable","Cần trả khách"],["paid","Đã trả khách"],["status","Trạng thái"],["deliveryStatus","Trạng thái giao hàng"]]), visible: ["code","invoice","time","customer","branch","handler","subtotal","afterDiscount","payable","paid","status"], filters: ["Loại trả hàng","Trạng thái","Thời gian","Người tạo","Người nhận trả","Kênh bán","Loại thu khác"] },
  "delivery-partners": { title: "Đối tác giao hàng", active: "delivery-partners", placeholder: "", prefix: "DTGH", statuses: { draft: "Đang hoạt động", completed: "Đang hoạt động", cancelled: "Ngừng hoạt động" }, columns: C([["code","Mã đối tác"],["partner","Tên đối tác"],["orders","Tổng đơn hàng"],["cod","Cần thu hộ (COD)"],["remainingCod","Còn cần thu (COD)"],["shippingFee","Tổng phí giao hàng"],["payable","Còn cần trả ĐTGH"]]), visible: ["code","partner","orders","cod","remainingCod","shippingFee","payable"], filters: [] },
  waybills: { title: "Vận đơn", active: "waybills", placeholder: "Theo mã vận đơn", prefix: "VD", statuses: { draft: "Đang xử lý", completed: "Hoàn thành", cancelled: "Đã hủy" }, columns: C([["code","Mã vận đơn"],["createdAt","Thời gian tạo"],["completedAt","Thời gian hoàn thành"],["creator","Người tạo"],["invoice","Mã hóa đơn"],["customerCode","Mã KH"],["customer","Khách hàng"],["branch","Chi nhánh"],["seller","Nhân viên bán"],["receiver","Người nhận"],["phone","Điện thoại"],["address","Địa chỉ"],["area","Khu vực"],["ward","Phường xã"],["partner","Đối tác giao hàng"],["deliveryNote","Ghi chú giao hàng"],["deliveryStatus","Trạng thái giao"],["deliveryAt","Thời gian giao hàng"],["service","Dịch vụ"],["cod","Cần thu hộ (COD)"],["shippingFee","Tổng cước phí"],["reconciliation","Mã đối soát"],["partnerFee","Phí trả ĐTGH"],["statusNote","Ghi chú trạng thái giao hàng"]]), visible: ["code","createdAt","invoice","customer","phone","partner","deliveryStatus","deliveryAt","cod","shippingFee"], filters: ["Trạng thái giao hàng","Đối tác giao hàng","Thời gian tạo","Thời gian hoàn thành","Khu vực giao hàng","Thu hộ tiền (COD)"] },
};
const PAGE_SIZE = 15; const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value); const dt = (value: string) => value && value !== "---" ? new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "---";

export default function OrderListClient({ mode, profile, products, customers, initialOrders }: { mode: Mode; profile: Profile; products: Product[]; customers: Customer[]; initialOrders: SourceOrder[] }) {
  const config = configs[mode]; const seeded = useMemo<GridRow[]>(() => mode === "orders" || mode === "invoices" ? initialOrders.map((order) => { const status: Status = order.status === "cancelled" ? "cancelled" : order.status === "draft" ? "draft" : "completed"; const prefix = mode === "orders" ? "DH" : "HD"; const code = `${prefix}${String(order.order_number).padStart(6, "0")}`; return { id: order.id, status, favorite: false, values: { code, orderCode: `DH${String(order.order_number).padStart(6, "0")}`, waybill: "---", invoice: mode === "invoices" ? code : "---", returnCode: "---", time: order.created_at, createdAt: order.created_at, updatedAt: order.updated_at || order.created_at, completedAt: status === "completed" ? order.updated_at || order.created_at : "---", deliveryAt: "---", waitingDays: 0, customerCode: "---", customer: order.customers?.name || "Khách lẻ", phone: order.customers?.phone || "---", address: "---", area: "---", birthday: "---", partner: "---", handler: profile.full_name, seller: profile.full_name, creator: profile.full_name, receiver: order.customers?.name || "Khách lẻ", channel: "Bán trực tiếp", note: "---", branch: "Chi nhánh trung tâm", subtotal: Number(order.subtotal), discount: Number(order.discount), afterDiscount: Number(order.total), payable: Number(order.total), paid: status === "completed" ? Number(order.total) : 0, deliveryStatus: "---", reconciliation: "---", taxDiscount: 0, paymentDiscount: 0, cod: 0, shippingFee: 0, partnerFee: 0, returnFee: 0, taxRefund: 0, otherRefund: 0, deliveryNote: "---", statusNote: "---", ward: "---", service: "---" } }; }) : [], [initialOrders, mode, profile.full_name]);
  const [rows, setRows] = useState<GridRow[]>(seeded); const [query, setQuery] = useState(""); const [showColumns, setShowColumns] = useState(false); const [showCreate, setShowCreate] = useState(false); const [notice, setNotice] = useState(""); const [statuses, setStatuses] = useState<Status[]>(["draft", "completed", "cancelled"]); const [datePreset, setDatePreset] = useState("month"); const [page, setPage] = useState(1); const importRef = useRef<HTMLInputElement>(null); const [visible, setVisible] = useState<Record<string, boolean>>(() => Object.fromEntries(config.columns.map((column) => [column.key, config.visible.includes(column.key)])));
  const [customerId, setCustomerId] = useState(customers[0]?.id || ""); const [note, setNote] = useState(""); const [productQuery, setProductQuery] = useState(""); const [quantities, setQuantities] = useState<Record<string, number>>({}); const [prices, setPrices] = useState<Record<string, number>>(() => Object.fromEntries(products.map((product) => [product.id, Number(product.price)])));
  const filtered = useMemo(() => rows.filter((row) => `${row.values.code || ""} ${row.values.customer || ""} ${row.values.phone || ""}`.toLowerCase().includes(query.toLowerCase()) && statuses.includes(row.status) && (datePreset === "all" || new Date(String(row.values.createdAt || new Date())).getMonth() === new Date().getMonth())), [rows, query, statuses, datePreset]); const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const safePage = Math.min(page, totalPages); const pageRows = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE); const modalProducts = products.filter((product) => `${product.sku} ${product.name}`.toLowerCase().includes(productQuery.toLowerCase())).slice(0, 40); const selectedCount = Object.values(quantities).filter((value) => value > 0).length;
  function toggleStatus(value: Status) { setStatuses((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); }
  function createRow(status: Exclude<Status, "cancelled">) { const selected = products.filter((product) => Number(quantities[product.id] || 0) > 0); if (!selected.length) return; const now = new Date(); const subtotal = selected.reduce((sum, product) => sum + Number(quantities[product.id]) * Number(prices[product.id] || 0), 0); const customer = customers.find((item) => item.id === customerId); const code = `${config.prefix}${String(Date.now()).slice(-8)}`; const values: Record<string, string | number> = { code, invoice: mode === "returns" ? "---" : code, orderCode: code, waybill: "---", time: now.toISOString(), createdAt: now.toISOString(), updatedAt: now.toISOString(), customer: customer?.name || "Khách lẻ", phone: customer?.phone || "---", customerCode: customer ? `KH${customer.id.slice(0, 6).toUpperCase()}` : "---", handler: profile.full_name, seller: profile.full_name, creator: profile.full_name, branch: "Chi nhánh trung tâm", channel: "Bán trực tiếp", note: note || "---", subtotal, discount: 0, afterDiscount: subtotal, payable: subtotal, paid: status === "completed" ? subtotal : 0, deliveryStatus: "---", partner: "---" }; setRows((current) => [{ id: crypto.randomUUID(), values, status, favorite: false }, ...current]); setShowCreate(false); setQuantities({}); setNote(""); setNotice(`Đã ${status === "draft" ? "lưu tạm" : "hoàn thành"} ${config.title.toLowerCase()} trong phiên làm việc.`); }
  function exportCsv() { const lines = [config.columns.map((column) => column.label), ...filtered.map((row) => config.columns.map((column) => column.key === "status" ? config.statuses[row.status] : row.values[column.key] ?? "---"))]; const csv = lines.map((line) => line.map((cell) => `"${String(cell).replaceAll("\"", "\"\"")}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `${mode}.csv`; a.click(); URL.revokeObjectURL(url); }
  function renderCell(row: GridRow, key: string) { if (["code", "invoice", "orderCode", "waybill"].includes(key)) return <b className="order-link">{row.values[key] ?? "---"}</b>; if (["time", "createdAt", "updatedAt", "completedAt", "deliveryAt"].includes(key)) return dt(String(row.values[key] || "---")); if (["subtotal", "discount", "afterDiscount", "payable", "paid", "cod", "shippingFee", "partnerFee", "returnFee", "taxRefund", "otherRefund", "remainingCod"].includes(key)) return money(Number(row.values[key] || 0)); if (key === "status") return <span className={`stock-status ${row.status === "completed" ? "balanced" : row.status}`}>{config.statuses[row.status]}</span>; return String(row.values[key] ?? "---"); }
  const hasFilters = config.filters.length > 0;
  return <div className="kv-shell product-page order-management-page"><ManagementHeader profile={profile} active={config.active} /><div className="product-actions order-actions"><h1>{config.title}</h1><div className="product-toolbar">{config.placeholder && <label className="product-query"><Search size={20} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={config.placeholder} /><SlidersHorizontal size={17} /></label>}{config.primary && <button className="primary" onClick={() => setShowCreate(true)}>＋ {config.primary}</button>}{config.secondary && <button onClick={() => setNotice("Chọn ít nhất hai đơn hàng để gộp đơn.")}>{config.secondary}</button>}{config.import && <><button onClick={() => importRef.current?.click()}><FileUp size={18} />Import file</button><input hidden type="file" ref={importRef} /></>}<button onClick={exportCsv}><Download size={18} />Xuất file</button><div className="column-control"><button aria-label="Chọn cột" onClick={() => setShowColumns((value) => !value)}><Columns3 size={19} /></button>{showColumns && <div className="columns-popover order-columns">{config.columns.map((column) => <label key={column.key}><input type="checkbox" checked={visible[column.key]} onChange={() => setVisible((current) => ({ ...current, [column.key]: !current[column.key] }))} />{column.label}</label>)}</div>}</div><button aria-label="Thiết lập"><Settings size={19} /></button><button aria-label="Hướng dẫn"><HelpCircle size={19} /></button></div></div>
    <main className={`product-workspace ${!hasFilters ? "no-order-sidebar" : ""}`}>{hasFilters && <aside className="product-filter-sidebar order-sidebar">{config.filters.map((filter, index) => <section key={filter}><h2>{filter}</h2>{filter.includes("Thời gian") ? <><label className="stock-radio"><input type="radio" name={`${mode}-${index}`} checked={datePreset === "month"} onChange={() => setDatePreset("month")} /><span>Tháng này</span></label><label className="stock-radio"><input type="radio" name={`${mode}-${index}`} checked={datePreset === "custom"} onChange={() => setDatePreset("custom")} /><span>Tùy chỉnh</span><CalendarDays size={17} /></label><label className="stock-radio"><input type="radio" name={`${mode}-${index}`} checked={datePreset === "all"} onChange={() => setDatePreset("all")} /><span>Toàn thời gian</span></label></> : filter.includes("Trạng thái") ? <>{(["draft","completed","cancelled"] as Status[]).map((value) => <label className="stock-check" key={value}><input type="checkbox" checked={statuses.includes(value)} onChange={() => toggleStatus(value)} />{config.statuses[value]}</label>)}</> : <select aria-label={filter}><option>Chọn {filter.toLowerCase()}</option></select>}</section>)}</aside>}
      <section className="product-content order-content">{notice && <div className="product-notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}<div className="product-table order-table"><table><thead><tr><th className="row-select"><input type="checkbox" aria-label="Chọn tất cả" /></th><th className="row-star"><Star size={16} /></th>{config.columns.filter((column) => visible[column.key]).map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{pageRows.map((row) => <tr key={row.id}><td className="row-select"><input type="checkbox" aria-label={`Chọn ${row.values.code}`} /></td><td className="row-star"><Star size={17} fill={row.favorite ? "#f5a623" : "none"} /></td>{config.columns.filter((column) => visible[column.key]).map((column) => <td className={["subtotal","discount","afterDiscount","payable","paid","cod","shippingFee"].includes(column.key) ? "number-cell" : ""} key={column.key}>{renderCell(row, column.key)}</td>)}</tr>)}{!pageRows.length && <tr><td colSpan={config.columns.filter((column) => visible[column.key]).length + 2}><div className="product-empty"><Columns3 size={46} /><strong>Không tìm thấy kết quả</strong><p>Không có dữ liệu {config.title.toLowerCase()} phù hợp.</p></div></td></tr>}</tbody></table></div><footer className="product-pager"><span>Hiển thị {filtered.length ? (safePage - 1) * PAGE_SIZE + 1 : 0}–{Math.min(safePage * PAGE_SIZE, filtered.length)} / {filtered.length}</span><div><button disabled={safePage === 1} onClick={() => setPage(safePage - 1)}>‹</button><button className="current">{safePage}</button><button disabled={safePage === totalPages} onClick={() => setPage(safePage + 1)}>›</button></div></footer></section></main><a className="kv-help" href="tel:0704040044">💬 <span>0704 04 0044</span></a>
    {showCreate && <div className="modal-backdrop"><section className="product-modal order-modal"><header><div><h2>{config.title}</h2><p>Chọn khách hàng và hàng hóa cho chứng từ</p></div><button onClick={() => setShowCreate(false)}>×</button></header><div className="order-form-head"><label>Khách hàng<select value={customerId} onChange={(event) => setCustomerId(event.target.value)}><option value="">Khách lẻ</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name} {customer.phone || ""}</option>)}</select></label><label>Ghi chú<input value={note} onChange={(event) => setNote(event.target.value)} /></label></div><label className="product-query order-product-search"><Search size={18} /><input value={productQuery} onChange={(event) => setProductQuery(event.target.value)} placeholder="Theo mã, tên hàng" /></label><div className="order-lines"><table><thead><tr><th>Mã hàng</th><th>Tên hàng</th><th>Tồn kho</th><th>Số lượng</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>{modalProducts.map((product) => { const qty = Number(quantities[product.id] || 0); const price = Number(prices[product.id] || 0); return <tr key={product.id}><td>{product.sku}</td><td>{product.name}</td><td>{product.stock_quantity}</td><td><input type="number" aria-label={`Số lượng ${product.name}`} min="0" value={qty} onChange={(event) => setQuantities((current) => ({ ...current, [product.id]: Math.max(0, Number(event.target.value)) }))} /></td><td><input type="number" aria-label={`Đơn giá ${product.name}`} min="0" value={price} onChange={(event) => setPrices((current) => ({ ...current, [product.id]: Math.max(0, Number(event.target.value)) }))} /></td><td>{money(qty * price)}</td></tr>})}{!modalProducts.length && <tr><td colSpan={6}>Không có hàng hóa</td></tr>}</tbody></table></div>{selectedCount === 0 && <p className="order-warning">Nhập số lượng cho ít nhất một hàng hóa để lưu.</p>}<footer><span>{selectedCount} hàng hóa được chọn</span><button onClick={() => setShowCreate(false)}>Hủy</button><button disabled={selectedCount === 0} onClick={() => createRow("draft")}>Lưu tạm</button><button disabled={selectedCount === 0} className="primary" onClick={() => createRow("completed")}><Check size={17} />Hoàn thành</button></footer></section></div>}
  </div>;
}
