"use client";

import { useMemo, useRef, useState } from "react";
import { Columns3, Download, FileUp, HelpCircle, Search, Settings, SlidersHorizontal, Star } from "lucide-react";
import ManagementHeader from "@/app/management-header";
import type { Profile } from "@/lib/auth";

type Supplier = { id: string; code: string; name: string; phone: string; group: string; address: string; area: string; company: string; note: string; taxCode: string; identity: string; creator: string; createdAt: string; debt: number; totalPurchase: number; netPurchase: number; active: boolean; favorite: boolean };
type ColumnKey = "code" | "name" | "phone" | "group" | "address" | "area" | "company" | "note" | "taxCode" | "identity" | "creator" | "createdAt" | "debt" | "totalPurchase" | "netPurchase" | "status";
const PAGE_SIZE = 15;
const columns: Array<{ key: ColumnKey; label: string }> = [{ key: "code", label: "Mã nhà cung cấp" }, { key: "name", label: "Tên nhà cung cấp" }, { key: "phone", label: "Điện thoại" }, { key: "group", label: "Nhóm nhà cung cấp" }, { key: "address", label: "Địa chỉ" }, { key: "area", label: "Khu vực" }, { key: "company", label: "Công ty" }, { key: "note", label: "Ghi chú" }, { key: "taxCode", label: "Mã số thuế" }, { key: "identity", label: "Số CCCD/CMND" }, { key: "creator", label: "Người tạo" }, { key: "createdAt", label: "Ngày tạo" }, { key: "debt", label: "Nợ cần trả hiện tại" }, { key: "totalPurchase", label: "Tổng mua" }, { key: "netPurchase", label: "Tổng mua trừ trả hàng" }, { key: "status", label: "Trạng thái" }];
const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value);
const formatDate = (value: string) => new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value));

export default function SuppliersClient({ profile, initialSuppliers }: { profile: Profile; initialSuppliers: Array<{ id: string; name: string; created_at?: string }> }) {
  const seed = useMemo<Supplier[]>(() => initialSuppliers.map((item, index) => ({ id: item.id, code: `NCC${String(index + 1).padStart(6, "0")}`, name: item.name, phone: "", group: "", address: "", area: "", company: "", note: "", taxCode: "", identity: "", creator: profile.full_name, createdAt: item.created_at || new Date().toISOString(), debt: 0, totalPurchase: 0, netPurchase: 0, active: true, favorite: false })), [initialSuppliers, profile.full_name]);
  const [items, setItems] = useState(seed); const [query, setQuery] = useState(""); const [groupFilter, setGroupFilter] = useState("all"); const [status, setStatus] = useState("all"); const [debtMin, setDebtMin] = useState(""); const [debtMax, setDebtMax] = useState(""); const [showCreate, setShowCreate] = useState(false); const [showColumns, setShowColumns] = useState(false); const [notice, setNotice] = useState(""); const [page, setPage] = useState(1); const importInput = useRef<HTMLInputElement>(null);
  const [form, setForm] = useState({ code: "", name: "", phone: "", group: "", address: "", area: "", company: "", note: "", taxCode: "", identity: "" });
  const [visible, setVisible] = useState<Record<ColumnKey, boolean>>({ code: true, name: true, phone: true, group: true, address: true, area: false, company: false, note: false, taxCode: false, identity: false, creator: false, createdAt: true, debt: true, totalPurchase: true, netPurchase: false, status: true });
  const groups = useMemo(() => Array.from(new Set(items.map((item) => item.group).filter(Boolean))), [items]);
  const filtered = useMemo(() => items.filter((item) => `${item.code} ${item.name} ${item.phone}`.toLowerCase().includes(query.toLowerCase()) && (groupFilter === "all" || item.group === groupFilter) && (status === "all" || (status === "active") === item.active) && (!debtMin || item.debt >= Number(debtMin)) && (!debtMax || item.debt <= Number(debtMax))), [items, query, groupFilter, status, debtMin, debtMax]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const safePage = Math.min(page, totalPages); const rows = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE);
  function createSupplier() { if (!form.name.trim()) return; const now = new Date(); setItems((current) => [{ id: crypto.randomUUID(), code: form.code.trim() || `NCC${String(Date.now()).slice(-6)}`, name: form.name.trim(), phone: form.phone.trim(), group: form.group.trim(), address: form.address.trim(), area: form.area.trim(), company: form.company.trim(), note: form.note.trim(), taxCode: form.taxCode.trim(), identity: form.identity.trim(), creator: profile.full_name, createdAt: now.toISOString(), debt: 0, totalPurchase: 0, netPurchase: 0, active: true, favorite: false }, ...current]); setForm({ code: "", name: "", phone: "", group: "", address: "", area: "", company: "", note: "", taxCode: "", identity: "" }); setShowCreate(false); setNotice("Đã thêm nhà cung cấp trong phiên làm việc; các trường mở rộng chưa được lưu vào Supabase."); }
  function exportCsv() { const lines = [columns.map((column) => column.label), ...filtered.map((item) => [item.code, item.name, item.phone, item.group, item.address, item.area, item.company, item.note, item.taxCode, item.identity, item.creator, formatDate(item.createdAt), item.debt, item.totalPurchase, item.netPurchase, item.active ? "Đang hoạt động" : "Ngừng hoạt động"])]; const csv = lines.map((line) => line.map((cell) => `"${String(cell).replaceAll("\"", "\"\"")}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "nha-cung-cap.csv"; a.click(); URL.revokeObjectURL(url); }
  async function importCsv() { const file = importInput.current?.files?.[0]; if (!file) return; const lines = (await file.text()).replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean).slice(1); const now = new Date().toISOString(); const added = lines.map((line, index) => { const cells = line.split(",").map((cell) => cell.replace(/^"|"$/g, "").replaceAll("\"\"", "\"")); return { id: crypto.randomUUID(), code: cells[0] || `NCC${Date.now()}${index}`, name: cells[1] || "Nhà cung cấp mới", phone: cells[2] || "", group: cells[3] || "", address: cells[4] || "", area: cells[5] || "", company: cells[6] || "", note: cells[7] || "", taxCode: cells[8] || "", identity: cells[9] || "", creator: profile.full_name, createdAt: now, debt: 0, totalPurchase: 0, netPurchase: 0, active: true, favorite: false }; }); setItems((current) => [...added, ...current]); setNotice(`Đã nhập ${added.length} nhà cung cấp trong phiên làm việc.`); }
  const cell = (item: Supplier, key: ColumnKey) => { if (key === "code" || key === "name") return <b className="purchase-link">{item[key]}</b>; if (key === "createdAt") return formatDate(item.createdAt); if (key === "status") return <span className={`supplier-status ${item.active ? "active" : "inactive"}`}>{item.active ? "Đang hoạt động" : "Ngừng hoạt động"}</span>; const raw = (item as unknown as Record<string, string | number | boolean>)[key]; if (["debt", "totalPurchase", "netPurchase"].includes(key)) return money(Number(raw)); return String(raw || "---"); };
  return <div className="kv-shell product-page purchasing-page suppliers-page"><ManagementHeader profile={profile} active="suppliers" /><div className="product-actions purchase-actions"><h1>Nhà cung cấp</h1><div className="product-toolbar"><label className="product-query"><Search size={20} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Theo mã, tên, số điện thoại" /><SlidersHorizontal size={17} /></label><button className="primary" onClick={() => setShowCreate(true)}>＋ Nhà cung cấp</button><button onClick={() => importInput.current?.click()}><FileUp size={18} />Import file</button><input hidden ref={importInput} type="file" accept=".csv" onChange={importCsv} /><button onClick={exportCsv}><Download size={18} />Xuất file</button><div className="column-control"><button aria-label="Chọn cột" onClick={() => setShowColumns((value) => !value)}><Columns3 size={19} /></button>{showColumns && <div className="columns-popover purchase-columns">{columns.map((column) => <label key={column.key}><input type="checkbox" checked={visible[column.key]} onChange={() => setVisible((current) => ({ ...current, [column.key]: !current[column.key] }))} />{column.label}</label>)}</div>}</div><button aria-label="Thiết lập"><Settings size={19} /></button><button aria-label="Hướng dẫn"><HelpCircle size={19} /></button></div></div>
    <main className="product-workspace"><aside className="product-filter-sidebar purchase-sidebar"><section><h2>Nhóm nhà cung cấp</h2><select value={groupFilter} onChange={(event) => setGroupFilter(event.target.value)}><option value="all">Tất cả nhóm</option>{groups.map((group) => <option key={group}>{group}</option>)}</select></section><section><h2>Nợ hiện tại</h2><div className="debt-range"><input type="number" value={debtMin} onChange={(event) => setDebtMin(event.target.value)} placeholder="Từ" /><input type="number" value={debtMax} onChange={(event) => setDebtMax(event.target.value)} placeholder="Tới" /></div></section><section><h2>Trạng thái</h2>{[["all", "Tất cả"], ["active", "Đang hoạt động"], ["inactive", "Ngừng hoạt động"]].map(([value, label]) => <label className="stock-radio" key={value}><input type="radio" name="supplier-status" checked={status === value} onChange={() => setStatus(value)} /><span>{label}</span></label>)}</section></aside><section className="product-content purchase-content">{notice && <div className="product-notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}<div className="product-table purchase-table supplier-table"><table><thead><tr><th className="row-select"><input type="checkbox" aria-label="Chọn tất cả" /></th><th className="row-star"><Star size={16} /></th>{columns.filter((column) => visible[column.key]).map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td className="row-select"><input type="checkbox" aria-label={`Chọn ${item.name}`} /></td><td className="row-star"><button aria-label="Đánh dấu" onClick={() => setItems((current) => current.map((row) => row.id === item.id ? { ...row, favorite: !row.favorite } : row))}><Star size={17} fill={item.favorite ? "#f5a623" : "none"} /></button></td>{columns.filter((column) => visible[column.key]).map((column) => <td className={["debt", "totalPurchase", "netPurchase"].includes(column.key) ? "number-cell" : ""} key={column.key}>{cell(item, column.key)}</td>)}</tr>)}{!rows.length && <tr><td colSpan={columns.filter((column) => visible[column.key]).length + 2}><div className="product-empty"><Columns3 size={46} /><strong>Không tìm thấy kết quả</strong><p>Không có nhà cung cấp phù hợp với bộ lọc hiện tại.</p></div></td></tr>}</tbody></table></div><footer className="product-pager"><span>Hiển thị {filtered.length ? (safePage - 1) * PAGE_SIZE + 1 : 0}–{Math.min(safePage * PAGE_SIZE, filtered.length)} / {filtered.length} nhà cung cấp</span><div><button disabled={safePage === 1} onClick={() => setPage(safePage - 1)}>‹</button><button className="current">{safePage}</button><button disabled={safePage === totalPages} onClick={() => setPage(safePage + 1)}>›</button></div></footer></section></main><a className="kv-help" href="tel:0704040044">💬 <span>0704 04 0044</span></a>
    {showCreate && <div className="modal-backdrop"><section className="product-modal supplier-modal"><header><div><h2>Thêm nhà cung cấp</h2><p>Thông tin nhà cung cấp và liên hệ</p></div><button onClick={() => setShowCreate(false)}>×</button></header><div className="supplier-form">{([['code','Mã nhà cung cấp'],['name','Tên nhà cung cấp *'],['phone','Điện thoại'],['group','Nhóm nhà cung cấp'],['company','Công ty'],['taxCode','Mã số thuế'],['identity','Số CCCD/CMND'],['area','Khu vực'],['address','Địa chỉ'],['note','Ghi chú']] as Array<[keyof typeof form,string]>).map(([key,label]) => <label className={key === "address" || key === "note" ? "wide" : ""} key={key}>{label}<input autoFocus={key === "name"} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}</div><footer><button onClick={() => setShowCreate(false)}>Hủy</button><button className="primary" disabled={!form.name.trim()} onClick={createSupplier}>Lưu</button></footer></section></div>}
  </div>;
}
