"use client";

import { useMemo, useState } from "react";
import { CalendarDays, Check, ChevronLeft, ChevronRight, Columns3, Download, HelpCircle, Search, Settings, SlidersHorizontal, Star } from "lucide-react";
import ManagementHeader from "@/app/management-header";
import type { Profile } from "@/lib/auth";

type Product = { id: string; name: string; sku: string; price: number; cost?: number; stock_quantity: number };
type Status = "draft" | "completed" | "cancelled";
type Voucher = { id: string; code: string; purpose: string; totalValue: number; time: string; branch: string; note: string; status: Status; createdAt: string; exporter: string; creator: string; receiver: string; favorite: boolean };
type ColumnKey = "code" | "purpose" | "totalValue" | "time" | "branch" | "note" | "status" | "createdAt" | "exporter" | "creator" | "receiver";

const PAGE_SIZE = 15;
const columns: Array<{ key: ColumnKey; label: string }> = [{ key: "code", label: "Mã xuất dùng nội bộ" }, { key: "purpose", label: "Loại xuất" }, { key: "totalValue", label: "Tổng giá trị" }, { key: "time", label: "Thời gian" }, { key: "branch", label: "Chi nhánh" }, { key: "note", label: "Ghi chú" }, { key: "status", label: "Trạng thái" }, { key: "createdAt", label: "Thời gian tạo" }, { key: "exporter", label: "Người xuất" }, { key: "creator", label: "Người tạo" }, { key: "receiver", label: "Người nhận" }];
const statusLabel: Record<Status, string> = { draft: "Phiếu tạm", completed: "Hoàn thành", cancelled: "Đã hủy" };
const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value);
const dateTime = (value: string) => new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

export default function InternalUseClient({ profile, initialProducts }: { profile: Profile; initialProducts: Product[] }) {
  const [vouchers, setVouchers] = useState<Voucher[]>([]); const [query, setQuery] = useState(""); const [datePreset, setDatePreset] = useState("month");
  const [statuses, setStatuses] = useState<Status[]>(["draft", "completed", "cancelled"]); const [creatorFilter, setCreatorFilter] = useState("all"); const [exporterFilter, setExporterFilter] = useState("all"); const [receiverFilter, setReceiverFilter] = useState("all"); const [purposeFilter, setPurposeFilter] = useState("all");
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false); const [showColumns, setShowColumns] = useState(false); const [showCreate, setShowCreate] = useState(false); const [notice, setNotice] = useState(""); const [page, setPage] = useState(1);
  const [productQuery, setProductQuery] = useState(""); const [purpose, setPurpose] = useState("Sử dụng nội bộ"); const [receiver, setReceiver] = useState(""); const [note, setNote] = useState(""); const [quantities, setQuantities] = useState<Record<string, number>>({});
  const [visible, setVisible] = useState<Record<ColumnKey, boolean>>({ code: true, purpose: true, totalValue: true, time: true, branch: true, note: true, status: true, createdAt: false, exporter: true, creator: false, receiver: true });

  const filtered = useMemo(() => vouchers.filter((item) => {
    const now = new Date(); const created = new Date(item.createdAt); const date = datePreset === "all" || (datePreset === "today" ? created.toDateString() === now.toDateString() : created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear());
    return `${item.code} ${item.note}`.toLowerCase().includes(query.toLowerCase()) && statuses.includes(item.status) && (creatorFilter === "all" || item.creator === creatorFilter) && (exporterFilter === "all" || item.exporter === exporterFilter) && (receiverFilter === "all" || item.receiver === receiverFilter) && (purposeFilter === "all" || item.purpose === purposeFilter) && date;
  }), [vouchers, query, statuses, creatorFilter, exporterFilter, receiverFilter, purposeFilter, datePreset]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const safePage = Math.min(page, totalPages); const rows = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE);
  const modalProducts = initialProducts.filter((product) => `${product.sku} ${product.name}`.toLowerCase().includes(productQuery.toLowerCase())).slice(0, 40);
  const selectedCount = Object.values(quantities).filter((value) => value > 0).length;

  function toggleStatus(status: Status) { setStatuses((current) => current.includes(status) ? current.filter((value) => value !== status) : [...current, status]); setPage(1); }
  function saveVoucher(status: Exclude<Status, "cancelled">) {
    const selected = initialProducts.filter((product) => Number(quantities[product.id] || 0) > 0); if (!selected.length) { setNotice("Vui lòng nhập số lượng cho ít nhất một hàng hóa."); return; }
    const now = new Date(); const totalValue = selected.reduce((sum, product) => sum + Number(quantities[product.id]) * Number(product.cost || product.price || 0), 0);
    setVouchers((current) => [{ id: crypto.randomUUID(), code: `XNB${String(Date.now()).slice(-8)}`, purpose, totalValue, time: now.toISOString(), branch: "Chi nhánh trung tâm", note: note.trim(), status, createdAt: now.toISOString(), exporter: profile.full_name, creator: profile.full_name, receiver: receiver.trim() || profile.full_name, favorite: false }, ...current]);
    setShowCreate(false); setQuantities({}); setProductQuery(""); setNote(""); setReceiver(""); setNotice(status === "draft" ? "Đã lưu phiếu tạm trong phiên làm việc." : "Đã hoàn thành phiếu trong phiên làm việc; tồn kho chưa được trừ trong cơ sở dữ liệu.");
  }
  function exportCsv() {
    const lines = [columns.map((column) => column.label), ...filtered.map((item) => [item.code, item.purpose, item.totalValue, dateTime(item.time), item.branch, item.note, statusLabel[item.status], dateTime(item.createdAt), item.exporter, item.creator, item.receiver])];
    const csv = lines.map((line) => line.map((cell) => `"${String(cell).replaceAll("\"", "\"\"")}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "xuat-dung-noi-bo.csv"; link.click(); URL.revokeObjectURL(url); setNotice(`Đã xuất ${filtered.length} phiếu.`);
  }
  const cell = (item: Voucher, key: ColumnKey) => { if (key === "code") return <b className="internal-code">{item.code}</b>; if (key === "totalValue") return money(item.totalValue); if (key === "time" || key === "createdAt") return dateTime(item[key]); if (key === "status") return <span className={`stock-status ${item.status === "completed" ? "balanced" : item.status}`}>{statusLabel[item.status]}</span>; return item[key]; };

  return <div className="kv-shell product-page internal-use-page"><ManagementHeader profile={profile} active="internal-use" />
    <div className="product-actions internal-actions"><h1>Xuất dùng nội bộ</h1><div className="product-toolbar"><label className="product-query"><Search size={20} /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Theo mã xuất dùng nội bộ" /><SlidersHorizontal size={17} /></label><button className="primary" onClick={() => setShowCreate(true)}>＋ Xuất dùng nội bộ</button><button onClick={exportCsv}><Download size={18} />Xuất file</button><div className="column-control"><button aria-label="Chọn cột" aria-expanded={showColumns} onClick={() => setShowColumns((value) => !value)}><Columns3 size={19} /></button>{showColumns && <div className="columns-popover internal-columns">{columns.map((column) => <label key={column.key}><input type="checkbox" checked={visible[column.key]} onChange={() => setVisible((current) => ({ ...current, [column.key]: !current[column.key] }))} />{column.label}</label>)}</div>}</div><button aria-label="Thiết lập"><Settings size={19} /></button><button aria-label="Hướng dẫn"><HelpCircle size={19} /></button></div></div>
    <main className={`product-workspace ${sidebarCollapsed ? "sidebar-is-collapsed" : ""}`}>{sidebarCollapsed ? <button className="sidebar-collapse collapsed" aria-label="Mở bộ lọc" onClick={() => setSidebarCollapsed(false)}><ChevronRight /></button> : <aside className="product-filter-sidebar internal-sidebar">
      <section><h2>Trạng thái</h2>{(["draft", "completed", "cancelled"] as Status[]).map((status) => <label className="stock-check" key={status}><input type="checkbox" checked={statuses.includes(status)} onChange={() => toggleStatus(status)} />{statusLabel[status]}</label>)}</section>
      <section><h2>Thời gian</h2><label className="stock-radio"><input type="radio" name="internal-date" checked={datePreset === "month"} onChange={() => setDatePreset("month")} /><span>Tháng này</span><ChevronRight size={17} /></label><label className="stock-radio"><input type="radio" name="internal-date" checked={datePreset === "today"} onChange={() => setDatePreset("today")} /><span>Tùy chỉnh</span><CalendarDays size={17} /></label><label className="stock-radio"><input type="radio" name="internal-date" checked={datePreset === "all"} onChange={() => setDatePreset("all")} /><span>Toàn thời gian</span></label></section>
      <section><h2>Người tạo</h2><select aria-label="Người tạo" value={creatorFilter} onChange={(event) => setCreatorFilter(event.target.value)}><option value="all">Chọn người tạo</option><option value={profile.full_name}>{profile.full_name}</option></select></section><section><h2>Người xuất dùng nội bộ</h2><select aria-label="Người xuất dùng nội bộ" value={exporterFilter} onChange={(event) => setExporterFilter(event.target.value)}><option value="all">Chọn người xuất</option><option value={profile.full_name}>{profile.full_name}</option></select></section><section><h2>Loại xuất</h2><select aria-label="Loại xuất" value={purposeFilter} onChange={(event) => setPurposeFilter(event.target.value)}><option value="all">Tất cả</option><option>Sử dụng nội bộ</option><option>Khác</option></select></section><section><h2>Người nhận</h2><select aria-label="Người nhận" value={receiverFilter} onChange={(event) => setReceiverFilter(event.target.value)}><option value="all">Chọn người nhận</option><option value={profile.full_name}>{profile.full_name}</option></select></section><button className="sidebar-collapse" aria-label="Thu gọn bộ lọc" onClick={() => setSidebarCollapsed(true)}><ChevronLeft /></button></aside>}
      <section className="product-content internal-content">{notice && <div className="product-notice" role="status">{notice}<button onClick={() => setNotice("")}>×</button></div>}<div className="product-table internal-table"><table><thead><tr><th className="stock-select"><input aria-label="Chọn tất cả" type="checkbox" /></th><th className="stock-star"><Star size={16} /></th>{columns.filter((column) => visible[column.key]).map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((item) => <tr className="product-row" key={item.id}><td className="stock-select"><input aria-label={`Chọn ${item.code}`} type="checkbox" /></td><td className="stock-star"><button aria-label="Đánh dấu" onClick={() => setVouchers((current) => current.map((row) => row.id === item.id ? { ...row, favorite: !row.favorite } : row))}><Star size={17} fill={item.favorite ? "#f5a623" : "none"} /></button></td>{columns.filter((column) => visible[column.key]).map((column) => <td className={column.key === "totalValue" ? "number-cell" : ""} key={column.key}>{cell(item, column.key)}</td>)}</tr>)}{!rows.length && <tr><td colSpan={columns.filter((column) => visible[column.key]).length + 2}><div className="product-empty internal-empty"><Columns3 size={46} /><strong>Không tìm thấy kết quả</strong><p>Không có phiếu xuất dùng nội bộ phù hợp với bộ lọc hiện tại.</p><button className="primary" onClick={() => setShowCreate(true)}>Xuất dùng nội bộ</button></div></td></tr>}</tbody></table></div><footer className="product-pager"><span>Hiển thị {filtered.length ? (safePage - 1) * PAGE_SIZE + 1 : 0}–{Math.min(safePage * PAGE_SIZE, filtered.length)} / {filtered.length} phiếu</span><div><button disabled={safePage === 1} onClick={() => setPage(safePage - 1)}>‹</button><button className="current">{safePage}</button><button disabled={safePage === totalPages} onClick={() => setPage(safePage + 1)}>›</button></div></footer></section>
    </main><a className="kv-help" href="tel:0704040044">💬 <span>0704 04 0044</span></a>
    {showCreate && <div className="modal-backdrop"><section className="product-modal internal-modal"><header><div><h2>Xuất dùng nội bộ</h2><p>Lập phiếu xuất hàng hóa phục vụ sử dụng nội bộ</p></div><button onClick={() => setShowCreate(false)}>×</button></header><div className="internal-form-head"><label>Loại xuất<select value={purpose} onChange={(event) => setPurpose(event.target.value)}><option>Sử dụng nội bộ</option><option>Khác</option></select></label><label>Người nhận<input value={receiver} onChange={(event) => setReceiver(event.target.value)} placeholder="Nhập người nhận" /></label><label>Ghi chú<input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Nhập ghi chú" /></label></div><label className="product-query internal-product-search"><Search size={18} /><input value={productQuery} onChange={(event) => setProductQuery(event.target.value)} placeholder="Theo mã, tên hàng" /></label><div className="internal-lines"><table><thead><tr><th>Mã hàng</th><th>Tên hàng</th><th>Tồn kho</th><th>Số lượng xuất</th><th>Giá trị</th></tr></thead><tbody>{modalProducts.map((product) => { const quantity = Number(quantities[product.id] || 0); return <tr key={product.id}><td>{product.sku}</td><td>{product.name}</td><td>{product.stock_quantity}</td><td><input aria-label={`Số lượng ${product.name}`} type="number" min="0" max={product.stock_quantity} value={quantity} onChange={(event) => setQuantities((current) => ({ ...current, [product.id]: Math.min(Number(product.stock_quantity), Math.max(0, Number(event.target.value))) }))} /></td><td>{money(quantity * Number(product.cost || product.price || 0))}</td></tr>})}{!modalProducts.length && <tr><td colSpan={5}>Không có hàng hóa</td></tr>}</tbody></table></div>{selectedCount === 0 && <p className="internal-form-warning">Nhập số lượng xuất cho ít nhất một hàng hóa để lưu phiếu.</p>}<footer><span>{selectedCount} hàng hóa được chọn</span><button onClick={() => setShowCreate(false)}>Hủy</button><button disabled={selectedCount === 0} onClick={() => saveVoucher("draft")}>Lưu tạm</button><button disabled={selectedCount === 0} className="primary" onClick={() => saveVoucher("completed")}><Check size={17} />Hoàn thành</button></footer></section></div>}
  </div>;
}
