-- Persistent sales orders, full-order returns, delivery partners and waybills.
alter table public.orders add column if not exists note text;
alter table public.orders add column if not exists channel text not null default 'direct';
alter table public.orders add column if not exists payment_method text;
alter table public.orders add column if not exists branch_id uuid references public.store_branches(id) on delete set null;
alter table public.customers add column if not exists customer_number bigint generated by default as identity;
alter table public.order_items add column if not exists affects_inventory boolean;
alter table public.order_items add column if not exists affects_branch_inventory boolean;
update public.order_items i set affects_inventory = case
  when o.status in ('paid'::public.order_status, 'refunded'::public.order_status) then exists(
    select 1 from public.inventory_movements movement
    where movement.reference_id = i.order_id and movement.product_id = i.product_id and movement.type = 'sale'::public.movement_type
  )
  else p.track_inventory
end
from public.orders o, public.products p
where o.id = i.order_id and p.id = i.product_id and i.affects_inventory is null;
update public.order_items set affects_branch_inventory = false where affects_branch_inventory is null;
alter table public.order_items alter column affects_inventory set default true;
alter table public.order_items alter column affects_inventory set not null;
alter table public.order_items alter column affects_branch_inventory set default false;
alter table public.order_items alter column affects_branch_inventory set not null;

-- Legacy stores started with one central branch. Allocate stock there only when
-- a product has never had any branch allocation, then attach legacy orders.
insert into public.product_branch_inventory(product_id, branch_id, quantity)
select p.id, b.id, p.stock_quantity
from public.products p
join lateral (
  select id from public.store_branches where store_id = p.store_id and active order by is_default desc, created_at limit 1
) b on true
where p.track_inventory and not exists(select 1 from public.product_branch_inventory inventory where inventory.product_id = p.id)
on conflict(product_id, branch_id) do nothing;
update public.orders o set branch_id = (
  select id from public.store_branches where store_id = o.store_id and active order by is_default desc, created_at limit 1
) where o.branch_id is null;

-- Sales documents must only be changed through the transactional functions below.
revoke insert, update on public.orders, public.order_items from authenticated;
drop policy if exists "members create orders" on public.orders;
drop policy if exists "manager or creator updates orders" on public.orders;
drop policy if exists "members create order items" on public.order_items;
drop policy if exists "members update order items" on public.order_items;
revoke insert, update on public.customers from authenticated;
grant insert(store_id, name, phone, email, created_by) on public.customers to authenticated;
grant update(name, phone, email) on public.customers to authenticated;

create table if not exists public.sales_returns (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  return_number bigint generated always as identity,
  order_id uuid not null references public.orders(id) on delete restrict,
  status text not null default 'completed' check (status in ('completed', 'cancelled')),
  subtotal numeric(14,2) not null default 0 check (subtotal between 0 and 999999999999.99),
  refund_amount numeric(14,2) not null default 0 check (refund_amount between 0 and 999999999999.99),
  note text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(store_id, order_id)
);

create table if not exists public.sales_return_items (
  id uuid primary key default gen_random_uuid(),
  return_id uuid not null references public.sales_returns(id) on delete cascade,
  product_id uuid not null references public.products(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(14,2) not null check (unit_price between 0 and 999999999999.99),
  line_total numeric(14,2) generated always as (quantity * unit_price) stored
);

create table if not exists public.delivery_partners (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  partner_number bigint generated always as identity,
  name text not null,
  phone text,
  active boolean not null default true,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(store_id, name)
);

create table if not exists public.shipments (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  shipment_number bigint generated always as identity,
  order_id uuid not null references public.orders(id) on delete restrict,
  partner_id uuid references public.delivery_partners(id) on delete set null,
  status text not null default 'pending_pickup' check (status in ('pending_pickup','picked_up','delivering','delivered','failed','returning','returned','cancelled')),
  receiver_name text not null,
  receiver_phone text,
  address text,
  area text,
  service text,
  cod_amount numeric(14,2) not null default 0 check (cod_amount between 0 and 999999999999.99),
  collected_cod numeric(14,2) not null default 0 check (collected_cod between 0 and cod_amount),
  shipping_fee numeric(14,2) not null default 0 check (shipping_fee between 0 and 999999999999.99),
  partner_fee numeric(14,2) not null default 0 check (partner_fee between 0 and 999999999999.99),
  note text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  delivery_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(store_id, order_id)
);

create table if not exists public.shipment_status_history (
  id uuid primary key default gen_random_uuid(),
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  status text not null check (status in ('pending_pickup','picked_up','delivering','delivered','failed','returning','returned','cancelled')),
  note text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

alter table public.sales_returns enable row level security;
alter table public.sales_return_items enable row level security;
alter table public.delivery_partners enable row level security;
alter table public.shipments enable row level security;
alter table public.shipment_status_history enable row level security;

grant select on public.sales_returns, public.sales_return_items, public.delivery_partners, public.shipments, public.shipment_status_history to authenticated;
grant insert, update on public.delivery_partners to authenticated;
grant all on public.sales_returns, public.sales_return_items, public.delivery_partners, public.shipments, public.shipment_status_history to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

drop policy if exists "members view sales returns" on public.sales_returns;
drop policy if exists "members view sales return items" on public.sales_return_items;
drop policy if exists "members view delivery partners" on public.delivery_partners;
drop policy if exists "managers manage delivery partners" on public.delivery_partners;
drop policy if exists "members view shipments" on public.shipments;
drop policy if exists "members view shipment history" on public.shipment_status_history;
create policy "members view sales returns" on public.sales_returns for select to authenticated using (store_id = (select public.current_store_id()));
create policy "members view sales return items" on public.sales_return_items for select to authenticated using (exists(select 1 from public.sales_returns r where r.id = return_id and r.store_id = (select public.current_store_id())));
create policy "members view delivery partners" on public.delivery_partners for select to authenticated using (store_id = (select public.current_store_id()));
create policy "managers manage delivery partners" on public.delivery_partners for all to authenticated using (store_id = (select public.current_store_id()) and (select public.current_app_role()) = 'manager') with check (store_id = (select public.current_store_id()) and (select public.current_app_role()) = 'manager');
create policy "members view shipments" on public.shipments for select to authenticated using (store_id = (select public.current_store_id()));
create policy "members view shipment history" on public.shipment_status_history for select to authenticated using (exists(select 1 from public.shipments s where s.id = shipment_id and s.store_id = (select public.current_store_id())));

create index if not exists sales_returns_store_created_idx on public.sales_returns(store_id, created_at desc);
create index if not exists sales_return_items_return_idx on public.sales_return_items(return_id);
create index if not exists delivery_partners_store_name_idx on public.delivery_partners(store_id, name);
create index if not exists shipments_store_created_idx on public.shipments(store_id, created_at desc);
create index if not exists shipments_partner_status_idx on public.shipments(store_id, partner_id, status);
create index if not exists shipment_history_shipment_idx on public.shipment_status_history(shipment_id, created_at);

create or replace function public.create_sales_order(
  p_customer_id uuid,
  p_status public.order_status,
  p_note text,
  p_items jsonb
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_store_id uuid := public.current_store_id();
  v_user_id uuid := auth.uid();
  v_order_id uuid;
  v_subtotal numeric(14,2);
  v_item_count integer;
  v_product_count integer;
  v_branch_id uuid;
begin
  if v_store_id is null or v_user_id is null then raise exception 'Phiên đăng nhập không hợp lệ'; end if;
  if public.current_app_role() is distinct from 'manager'::public.app_role then raise exception 'Bạn không có quyền tạo đơn hàng'; end if;
  if p_status not in ('draft'::public.order_status, 'paid'::public.order_status) then raise exception 'Trạng thái đơn hàng không hợp lệ'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Đơn hàng phải có ít nhất một hàng hóa'; end if;
  select id into v_branch_id from public.store_branches where store_id = v_store_id and active order by is_default desc, created_at limit 1;
  if v_branch_id is null then raise exception 'Cửa hàng chưa có chi nhánh hoạt động'; end if;

  if p_customer_id is not null and not exists(select 1 from public.customers c where c.id = p_customer_id and c.store_id = v_store_id) then
    raise exception 'Khách hàng không thuộc cửa hàng';
  end if;

  if exists(
    select 1 from jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric)
    where x.product_id is null or x.quantity is null or x.quantity <= 0 or x.unit_price is null or x.unit_price not between 0 and 999999999999.99
  ) then raise exception 'Chi tiết hàng hóa không hợp lệ'; end if;

  select count(*), count(distinct x.product_id) into v_item_count, v_product_count
  from jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric);
  if v_item_count <> v_product_count then raise exception 'Mỗi hàng hóa chỉ được xuất hiện một lần'; end if;

  perform p.id
  from public.products p
  join jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric) on x.product_id = p.id
  where p.store_id = v_store_id and p.active = true
  for update of p;

  select count(*) into v_product_count
  from public.products p
  join jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric) on x.product_id = p.id
  where p.store_id = v_store_id and p.active = true;
  if v_product_count <> v_item_count then raise exception 'Có hàng hóa không tồn tại hoặc không còn kinh doanh'; end if;
  if exists(
    select 1 from public.products p
    join jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric) on x.product_id = p.id
    where p.store_id = v_store_id and p.sold_by <> 'quantity'
  ) then raise exception 'Đơn hàng hiện chỉ hỗ trợ hàng hóa bán theo số lượng nguyên'; end if;

  perform i.product_id from public.product_branch_inventory i
  join jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric) on x.product_id = i.product_id
  where i.branch_id = v_branch_id for update of i;

  if p_status = 'paid'::public.order_status and exists(
    select 1
    from public.products p
    join jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric) on x.product_id = p.id
    left join public.product_branch_inventory i on i.product_id = p.id and i.branch_id = v_branch_id
    where p.track_inventory and (i.product_id is null or p.stock_quantity < x.quantity or i.quantity - i.reserved < x.quantity)
  ) then raise exception 'Tồn kho không đủ để hoàn thành hóa đơn'; end if;

  select coalesce(sum(x.quantity * x.unit_price), 0) into v_subtotal
  from jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric);

  insert into public.orders(store_id, customer_id, status, subtotal, discount, total, note, branch_id, created_by, updated_at)
  values(v_store_id, p_customer_id, p_status, v_subtotal, 0, v_subtotal, nullif(trim(p_note), ''), v_branch_id, v_user_id, now())
  returning id into v_order_id;

  insert into public.order_items(order_id, product_id, quantity, unit_price, affects_inventory, affects_branch_inventory)
  select v_order_id, x.product_id, x.quantity, x.unit_price, p.track_inventory, p.track_inventory
  from jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric)
  join public.products p on p.id = x.product_id and p.store_id = v_store_id;

  if p_status = 'paid'::public.order_status then
    update public.products p
    set stock_quantity = p.stock_quantity - x.quantity, updated_at = now()
    from jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric)
    where p.id = x.product_id and p.store_id = v_store_id and exists(select 1 from public.order_items i where i.order_id = v_order_id and i.product_id = p.id and i.affects_inventory);

    update public.product_branch_inventory i
    set quantity = i.quantity - x.quantity, updated_at = now()
    from jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric)
    where i.product_id = x.product_id and i.branch_id = v_branch_id and exists(select 1 from public.order_items line where line.order_id = v_order_id and line.product_id = i.product_id and line.affects_branch_inventory);

    insert into public.inventory_movements(store_id, product_id, type, quantity, reference_id, note, created_by)
    select v_store_id, x.product_id, 'sale'::public.movement_type, -x.quantity, v_order_id, 'Xuất bán theo hóa đơn', v_user_id
    from jsonb_to_recordset(p_items) as x(product_id uuid, quantity integer, unit_price numeric)
    join public.order_items i on i.order_id = v_order_id and i.product_id = x.product_id and i.affects_inventory;

    if p_customer_id is not null then
      update public.customers set total_spent = total_spent + v_subtotal where id = p_customer_id and store_id = v_store_id;
    end if;
  end if;

  return v_order_id;
end;
$$;

create or replace function public.transition_sales_order(p_order_id uuid, p_status public.order_status) returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_store_id uuid := public.current_store_id();
  v_user_id uuid := auth.uid();
  v_order public.orders%rowtype;
  v_branch_id uuid;
  v_subtotal numeric(14,2);
begin
  if public.current_app_role() is distinct from 'manager'::public.app_role then raise exception 'Bạn không có quyền cập nhật đơn hàng'; end if;
  if p_status is null or p_status not in ('paid'::public.order_status, 'cancelled'::public.order_status) then raise exception 'Trạng thái đơn hàng không hợp lệ'; end if;
  select * into v_order from public.orders where id = p_order_id and store_id = v_store_id for update;
  if not found then raise exception 'Không tìm thấy đơn hàng'; end if;
  if v_order.status <> 'draft'::public.order_status then raise exception 'Chỉ phiếu tạm mới được cập nhật'; end if;
  if p_status = 'cancelled'::public.order_status then
    update public.orders set status = p_status, updated_at = now() where id = p_order_id;
    return;
  end if;
  if not exists(select 1 from public.order_items where order_id = p_order_id) then raise exception 'Đơn hàng chưa có hàng hóa'; end if;
  if exists(
    select 1 from public.order_items i
    left join public.products p on p.id = i.product_id and p.store_id = v_store_id and p.active and p.sold_by = 'quantity'
    where i.order_id = p_order_id and p.id is null
  ) then raise exception 'Đơn hàng có hàng hóa không hợp lệ'; end if;
  if v_order.customer_id is not null and not exists(select 1 from public.customers where id = v_order.customer_id and store_id = v_store_id) then raise exception 'Khách hàng không thuộc cửa hàng'; end if;
  if exists(select 1 from public.order_items where order_id = p_order_id and (quantity <= 0 or unit_price not between 0 and 999999999999.99)) then raise exception 'Chi tiết hàng hóa không hợp lệ'; end if;
  select sum(line_total) into v_subtotal from public.order_items where order_id = p_order_id;
  if v_subtotal is null or v_subtotal not between 0 and 999999999999.99 then raise exception 'Tổng tiền đơn hàng không hợp lệ'; end if;

  v_branch_id := v_order.branch_id;
  if v_branch_id is null then
    select id into v_branch_id from public.store_branches where store_id = v_store_id and active order by is_default desc, created_at limit 1;
    if v_branch_id is null then raise exception 'Cửa hàng chưa có chi nhánh hoạt động'; end if;
  end if;
  update public.order_items set affects_branch_inventory = affects_inventory where order_id = p_order_id;
  perform p.id from public.products p join public.order_items i on i.product_id = p.id where i.order_id = p_order_id and p.store_id = v_store_id for update of p;
  perform inventory.product_id from public.product_branch_inventory inventory join public.order_items i on i.product_id = inventory.product_id where i.order_id = p_order_id and i.affects_branch_inventory and inventory.branch_id = v_branch_id for update of inventory;

  if exists(
    select 1
    from (select product_id, sum(quantity) as quantity from public.order_items where order_id = p_order_id and affects_branch_inventory group by product_id) sold
    join public.products p on p.id = sold.product_id and p.store_id = v_store_id
    left join public.product_branch_inventory inventory on inventory.product_id = sold.product_id and inventory.branch_id = v_branch_id
    where inventory.product_id is null or p.stock_quantity < sold.quantity or inventory.quantity - inventory.reserved < sold.quantity
  ) then raise exception 'Tồn kho không đủ để hoàn thành hóa đơn'; end if;

  update public.products p
  set stock_quantity = p.stock_quantity - sold.quantity, updated_at = now()
  from (select product_id, sum(quantity) as quantity from public.order_items where order_id = p_order_id and affects_inventory group by product_id) sold
  where p.id = sold.product_id and p.store_id = v_store_id;
  update public.product_branch_inventory inventory
  set quantity = inventory.quantity - sold.quantity, updated_at = now()
  from (select product_id, sum(quantity) as quantity from public.order_items where order_id = p_order_id and affects_branch_inventory group by product_id) sold
  where inventory.product_id = sold.product_id and inventory.branch_id = v_branch_id;
  insert into public.inventory_movements(store_id, product_id, type, quantity, reference_id, note, created_by)
  select v_store_id, sold.product_id, 'sale'::public.movement_type, -sold.quantity, p_order_id, 'Xuất bán theo hóa đơn', v_user_id
  from (select product_id, sum(quantity) as quantity from public.order_items where order_id = p_order_id and affects_inventory group by product_id) sold;
  if v_order.customer_id is not null then
    update public.customers set total_spent = total_spent + v_subtotal where id = v_order.customer_id and store_id = v_store_id;
  end if;
  update public.orders set status = 'paid'::public.order_status, subtotal = v_subtotal, discount = 0, total = v_subtotal, branch_id = v_branch_id, updated_at = now() where id = p_order_id;
end;
$$;

create or replace function public.refund_sales_order(p_order_id uuid, p_note text) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_store_id uuid := public.current_store_id();
  v_user_id uuid := auth.uid();
  v_order public.orders%rowtype;
  v_return_id uuid;
  v_shipment_status text;
  v_shipment_cod numeric(14,2);
  v_collected_cod numeric(14,2);
  v_subtotal numeric(14,2);
begin
  if public.current_app_role() is distinct from 'manager'::public.app_role then raise exception 'Bạn không có quyền trả hàng'; end if;
  select * into v_order from public.orders where id = p_order_id and store_id = v_store_id for update;
  if not found then raise exception 'Không tìm thấy hóa đơn'; end if;
  if v_order.status <> 'paid'::public.order_status then raise exception 'Chỉ hóa đơn hoàn thành mới được trả hàng'; end if;
  if exists(select 1 from public.sales_returns where order_id = p_order_id and store_id = v_store_id) then raise exception 'Hóa đơn đã được trả hàng'; end if;
  select status, cod_amount, collected_cod into v_shipment_status, v_shipment_cod, v_collected_cod from public.shipments where order_id = p_order_id and store_id = v_store_id for update;
  if v_shipment_status in ('pending_pickup','picked_up','delivering','failed','returning') then raise exception 'Không thể trả hóa đơn khi vận đơn đang xử lý'; end if;
  if v_shipment_status = 'delivered' and v_collected_cod < v_shipment_cod then raise exception 'Không thể trả hóa đơn khi COD chưa thu đủ'; end if;
  if exists(
    select 1 from public.order_items i
    left join public.products p on p.id = i.product_id and p.store_id = v_store_id
    where i.order_id = p_order_id and p.id is null
  ) then raise exception 'Hóa đơn có hàng hóa không thuộc cửa hàng'; end if;
  if v_order.customer_id is not null and not exists(select 1 from public.customers where id = v_order.customer_id and store_id = v_store_id) then raise exception 'Khách hàng không thuộc cửa hàng'; end if;
  if exists(select 1 from public.order_items where order_id = p_order_id and (quantity <= 0 or unit_price not between 0 and 999999999999.99)) then raise exception 'Chi tiết hàng hóa không hợp lệ'; end if;
  select sum(line_total) into v_subtotal from public.order_items where order_id = p_order_id;
  if v_subtotal is null or v_subtotal not between 0 and 999999999999.99 or v_order.subtotal <> v_subtotal or v_order.discount not between 0 and v_subtotal or v_order.total <> v_subtotal - v_order.discount then raise exception 'Tổng tiền hóa đơn không hợp lệ'; end if;
  if exists(select 1 from public.order_items where order_id = p_order_id and affects_branch_inventory) and (v_order.branch_id is null or not exists(select 1 from public.store_branches where id = v_order.branch_id and store_id = v_store_id)) then raise exception 'Chi nhánh hóa đơn không hợp lệ'; end if;
  perform p.id from public.products p join public.order_items i on i.product_id = p.id where i.order_id = p_order_id and p.store_id = v_store_id for update of p;
  perform i.product_id from public.product_branch_inventory i join public.order_items oi on oi.product_id = i.product_id where oi.order_id = p_order_id and oi.affects_branch_inventory and i.branch_id = v_order.branch_id for update of i;
  if exists(
    select 1 from public.order_items line
    left join public.product_branch_inventory inventory on inventory.product_id = line.product_id and inventory.branch_id = v_order.branch_id
    where line.order_id = p_order_id and line.affects_branch_inventory and inventory.product_id is null
  ) then raise exception 'Tồn kho chi nhánh của hóa đơn không hợp lệ'; end if;

  insert into public.sales_returns(store_id, order_id, status, subtotal, refund_amount, note, created_by)
  values(v_store_id, p_order_id, 'completed', v_order.subtotal, v_order.total, nullif(trim(p_note), ''), v_user_id)
  returning id into v_return_id;

  insert into public.sales_return_items(return_id, product_id, quantity, unit_price)
  select v_return_id, product_id, quantity, unit_price from public.order_items where order_id = p_order_id;

  update public.products p
  set stock_quantity = p.stock_quantity + i.quantity, updated_at = now()
  from (select product_id, sum(quantity) as quantity from public.order_items where order_id = p_order_id and affects_inventory group by product_id) i
  where p.id = i.product_id and p.store_id = v_store_id;

  update public.product_branch_inventory i
  set quantity = i.quantity + returned.quantity, updated_at = now()
  from (select product_id, sum(quantity) as quantity from public.order_items where order_id = p_order_id and affects_branch_inventory group by product_id) returned
  where i.product_id = returned.product_id and i.branch_id = v_order.branch_id;

  insert into public.inventory_movements(store_id, product_id, type, quantity, reference_id, note, created_by)
  select v_store_id, returned.product_id, 'return'::public.movement_type, returned.quantity, v_return_id, 'Nhập lại tồn do trả hàng bán', v_user_id
  from (select product_id, sum(quantity) as quantity from public.order_items where order_id = p_order_id and affects_inventory group by product_id) returned;

  update public.orders set status = 'refunded'::public.order_status, updated_at = now() where id = p_order_id;
  if v_order.customer_id is not null then
    update public.customers set total_spent = greatest(0, total_spent - v_order.total) where id = v_order.customer_id and store_id = v_store_id;
  end if;
  return v_return_id;
end;
$$;

create or replace function public.create_shipment(
  p_order_id uuid,
  p_partner_id uuid,
  p_receiver_name text,
  p_receiver_phone text,
  p_address text,
  p_area text,
  p_cod_amount numeric,
  p_shipping_fee numeric,
  p_partner_fee numeric,
  p_note text
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_store_id uuid := public.current_store_id();
  v_user_id uuid := auth.uid();
  v_shipment_id uuid;
  v_order public.orders%rowtype;
begin
  if public.current_app_role() is distinct from 'manager'::public.app_role then raise exception 'Bạn không có quyền tạo vận đơn'; end if;
  select * into v_order from public.orders where id = p_order_id and store_id = v_store_id for update;
  if not found or v_order.status <> 'paid'::public.order_status then raise exception 'Chỉ hóa đơn hoàn thành mới được tạo vận đơn'; end if;
  if p_partner_id is not null and not exists(select 1 from public.delivery_partners where id = p_partner_id and store_id = v_store_id and active) then raise exception 'Đối tác giao hàng không hợp lệ'; end if;
  if coalesce(trim(p_receiver_name), '') = '' then raise exception 'Người nhận là bắt buộc'; end if;
  if coalesce(p_cod_amount, 0) not between 0 and 999999999999.99 or coalesce(p_shipping_fee, 0) not between 0 and 999999999999.99 or coalesce(p_partner_fee, 0) not between 0 and 999999999999.99 then raise exception 'Số tiền vận đơn không hợp lệ'; end if;
  if coalesce(p_cod_amount, 0) > v_order.total + coalesce(p_shipping_fee, 0) then raise exception 'Tiền thu hộ vượt quá giá trị hóa đơn và phí giao hàng'; end if;

  insert into public.shipments(store_id, order_id, partner_id, receiver_name, receiver_phone, address, area, cod_amount, shipping_fee, partner_fee, note, created_by)
  values(v_store_id, p_order_id, p_partner_id, trim(p_receiver_name), nullif(trim(p_receiver_phone), ''), nullif(trim(p_address), ''), nullif(trim(p_area), ''), coalesce(p_cod_amount, 0), coalesce(p_shipping_fee, 0), coalesce(p_partner_fee, 0), nullif(trim(p_note), ''), v_user_id)
  returning id into v_shipment_id;
  insert into public.shipment_status_history(shipment_id, status, note, created_by) values(v_shipment_id, 'pending_pickup', 'Tạo vận đơn', v_user_id);
  return v_shipment_id;
end;
$$;

drop function if exists public.transition_shipment(uuid, text, text);
create or replace function public.transition_shipment(p_shipment_id uuid, p_status text, p_note text, p_collected_cod numeric) returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_store_id uuid := public.current_store_id();
  v_user_id uuid := auth.uid();
  v_current text;
  v_cod_amount numeric(14,2);
  v_allowed boolean := false;
begin
  if public.current_app_role() is distinct from 'manager'::public.app_role then raise exception 'Bạn không có quyền cập nhật vận đơn'; end if;
  select status, cod_amount into v_current, v_cod_amount from public.shipments where id = p_shipment_id and store_id = v_store_id for update;
  if not found then raise exception 'Không tìm thấy vận đơn'; end if;
  v_allowed := case v_current
    when 'pending_pickup' then p_status in ('picked_up','cancelled')
    when 'picked_up' then p_status in ('delivering','returning')
    when 'delivering' then p_status in ('delivered','failed','returning')
    when 'failed' then p_status in ('delivering','returning')
    when 'returning' then p_status = 'returned'
    else false end;
  if not v_allowed then raise exception 'Chuyển trạng thái vận đơn không hợp lệ'; end if;
  if p_status = 'delivered' and (p_collected_cod is null or p_collected_cod not between 0 and v_cod_amount) then raise exception 'Tiền COD thực thu không hợp lệ'; end if;
  if p_status <> 'delivered' and p_collected_cod is not null then raise exception 'Chỉ ghi nhận COD khi giao thành công'; end if;

  update public.shipments set
    status = p_status,
    delivery_at = case when p_status = 'delivering' and delivery_at is null then now() else delivery_at end,
    completed_at = case when p_status in ('delivered','returned','cancelled') then now() else completed_at end,
    collected_cod = case when p_status = 'delivered' then p_collected_cod else collected_cod end,
    updated_at = now()
  where id = p_shipment_id;
  insert into public.shipment_status_history(shipment_id, status, note, created_by) values(p_shipment_id, p_status, nullif(trim(p_note), ''), v_user_id);
end;
$$;

revoke all on function public.create_sales_order(uuid, public.order_status, text, jsonb) from public;
revoke all on function public.transition_sales_order(uuid, public.order_status) from public;
revoke all on function public.refund_sales_order(uuid, text) from public;
revoke all on function public.create_shipment(uuid, uuid, text, text, text, text, numeric, numeric, numeric, text) from public;
revoke all on function public.transition_shipment(uuid, text, text, numeric) from public;
grant execute on function public.create_sales_order(uuid, public.order_status, text, jsonb) to authenticated, service_role;
grant execute on function public.transition_sales_order(uuid, public.order_status) to authenticated, service_role;
grant execute on function public.refund_sales_order(uuid, text) to authenticated, service_role;
grant execute on function public.create_shipment(uuid, uuid, text, text, text, text, numeric, numeric, numeric, text) to authenticated, service_role;
grant execute on function public.transition_shipment(uuid, text, text, numeric) to authenticated, service_role;
